
public class Test21 {

    public static void main(String[] args) {
        Vreca prva = new Vreca();

        prva.dodaj(466, 2);
        prva.dodaj(1314, 4);
        prva.dodaj(1191, 2);
        prva.dodaj(535, 1);
        prva.dodaj(750, 4);
        prva.dodaj(1181, 3);
        prva.dodaj(1732, 3);
        prva.dodaj(1829, 5);
        prva.dodaj(1191, 2);
        prva.dodaj(1034, 5);
        prva.dodaj(226, 1);
        prva.dodaj(1829, 1);
        prva.dodaj(1500, 1);
        prva.dodaj(1314, 4);
        prva.dodaj(1500, 3);
        prva.dodaj(1806, 3);
        prva.dodaj(626, 5);
        prva.dodaj(1010, 2);
        prva.dodaj(1988, 1);
        prva.dodaj(1648, 4);
        prva.dodaj(1828, 4);
        prva.dodaj(1367, 4);
        prva.dodaj(1829, 1);
        prva.dodaj(879, 1);
        prva.dodaj(1454, 5);
        prva.dodaj(815, 5);
        prva.dodaj(1732, 3);
        prva.dodaj(1433, 2);
        prva.dodaj(359, 5);
        prva.dodaj(879, 5);
        prva.dodaj(1367, 3);
        prva.dodaj(1858, 3);
        prva.dodaj(1500, 1);
        prva.dodaj(750, 2);
        prva.dodaj(1858, 4);
        prva.dodaj(1956, 2);
        prva.dodaj(476, 4);
        prva.dodaj(1034, 3);
        prva.dodaj(1644, 4);
        prva.dodaj(946, 2);
        prva.dodaj(1806, 1);
        prva.dodaj(1034, 2);
        prva.dodaj(413, 5);
        prva.dodaj(1732, 4);
        prva.dodaj(476, 2);
        prva.dodaj(1034, 3);
        prva.dodaj(524, 1);
        prva.dodaj(1732, 1);
        prva.dodaj(626, 5);
        prva.dodaj(466, 1);
        prva.dodaj(1858, 1);
        prva.dodaj(783, 5);
        prva.dodaj(946, 5);
        prva.dodaj(879, 5);
        prva.dodaj(650, 1);
        prva.dodaj(1828, 5);
        prva.dodaj(1367, 3);
        prva.dodaj(476, 2);
        prva.dodaj(118, 2);
        prva.dodaj(1171, 1);
        prva.dodaj(946, 3);
        prva.dodaj(1181, 1);
        prva.dodaj(1367, 4);
        prva.dodaj(1911, 3);
        prva.dodaj(879, 5);
        prva.dodaj(206, 5);
        prva.dodaj(226, 3);
        prva.dodaj(1644, 3);
        prva.dodaj(1956, 5);
        prva.dodaj(1547, 4);
        prva.dodaj(650, 3);
        prva.dodaj(1095, 5);
        prva.dodaj(1648, 1);
        prva.dodaj(626, 5);
        prva.dodaj(626, 3);
        prva.dodaj(226, 3);
        prva.dodaj(482, 3);
        prva.dodaj(40, 3);
        prva.dodaj(879, 1);
        prva.dodaj(1191, 2);
        prva.dodaj(626, 4);
        prva.dodaj(95, 1);
        prva.dodaj(1745, 5);
        prva.dodaj(1034, 4);
        prva.dodaj(880, 1);
        prva.dodaj(40, 3);
        prva.dodaj(1829, 3);
        prva.dodaj(783, 5);
        prva.dodaj(783, 2);
        prva.dodaj(626, 1);
        prva.dodaj(1367, 4);
        prva.dodaj(1985, 3);
        prva.dodaj(1367, 3);
        prva.dodaj(1171, 5);
        prva.dodaj(815, 3);
        prva.dodaj(1191, 5);
        prva.dodaj(1828, 1);
        prva.dodaj(750, 2);
        prva.dodaj(40, 5);
        prva.dodaj(482, 1);

        Vreca druga = new Vreca(prva);
        druga.odstrani(40, 3);
        druga.odstrani(1454, 5);
        druga.odstrani(650, 4);
        druga.odstrani(413, 5);
        druga.odstrani(879, 2);
        druga.odstrani(946, 3);

        System.out.println(prva.steviloKopij(95));
        System.out.println(prva.steviloKopij(1644));
        System.out.println(prva.steviloKopij(1911));
        System.out.println(prva.steviloKopij(1500));
        System.out.println(prva.steviloKopij(226));
        System.out.println(prva.steviloKopij(1191));
        System.out.println(prva.steviloKopij(40));
        System.out.println(prva.steviloKopij(783));
        System.out.println(prva.steviloKopij(1171));
        System.out.println(prva.steviloKopij(1314));
        System.out.println(prva.steviloKopij(1534));
        System.out.println(prva.steviloKopij(1367));
        System.out.println(prva.steviloKopij(466));
        System.out.println(prva.steviloKopij(1433));
        System.out.println(prva.steviloKopij(206));
        System.out.println(prva.steviloKopij(1988));
        System.out.println(prva.steviloKopij(750));
        System.out.println(prva.steviloKopij(1547));
        System.out.println(prva.steviloKopij(868));
        System.out.println(prva.steviloKopij(1010));
        System.out.println(prva.steviloKopij(1829));
        System.out.println(prva.steviloKopij(880));
        System.out.println(prva.steviloKopij(1034));
        System.out.println(prva.steviloKopij(413));
        System.out.println(prva.steviloKopij(1933));
        System.out.println(prva.steviloKopij(1828));
        System.out.println(prva.steviloKopij(1827));
        System.out.println(prva.steviloKopij(359));
        System.out.println(prva.steviloKopij(1181));
        System.out.println(prva.steviloKopij(482));
        System.out.println(prva.steviloKopij(1806));
        System.out.println(prva.steviloKopij(650));
        System.out.println(prva.steviloKopij(879));
        System.out.println(prva.steviloKopij(1454));
        System.out.println(prva.steviloKopij(1858));
        System.out.println(prva.steviloKopij(1985));
        System.out.println(prva.steviloKopij(1095));
        System.out.println(prva.steviloKopij(1956));
        System.out.println(prva.steviloKopij(1732));
        System.out.println(prva.steviloKopij(535));
        System.out.println(prva.steviloKopij(1184));
        System.out.println(prva.steviloKopij(1745));
        System.out.println(prva.steviloKopij(118));
        System.out.println(prva.steviloKopij(476));
        System.out.println(prva.steviloKopij(524));
        System.out.println(prva.steviloKopij(1648));
        System.out.println(prva.steviloKopij(946));
        System.out.println(prva.steviloKopij(1169));
        System.out.println(prva.steviloKopij(815));
        System.out.println(prva.steviloKopij(626));

        System.out.println(druga.steviloKopij(95));
        System.out.println(druga.steviloKopij(1644));
        System.out.println(druga.steviloKopij(1911));
        System.out.println(druga.steviloKopij(1500));
        System.out.println(druga.steviloKopij(226));
        System.out.println(druga.steviloKopij(1191));
        System.out.println(druga.steviloKopij(40));
        System.out.println(druga.steviloKopij(783));
        System.out.println(druga.steviloKopij(1171));
        System.out.println(druga.steviloKopij(1314));
        System.out.println(druga.steviloKopij(1534));
        System.out.println(druga.steviloKopij(1367));
        System.out.println(druga.steviloKopij(466));
        System.out.println(druga.steviloKopij(1433));
        System.out.println(druga.steviloKopij(206));
        System.out.println(druga.steviloKopij(1988));
        System.out.println(druga.steviloKopij(750));
        System.out.println(druga.steviloKopij(1547));
        System.out.println(druga.steviloKopij(868));
        System.out.println(druga.steviloKopij(1010));
        System.out.println(druga.steviloKopij(1829));
        System.out.println(druga.steviloKopij(880));
        System.out.println(druga.steviloKopij(1034));
        System.out.println(druga.steviloKopij(413));
        System.out.println(druga.steviloKopij(1933));
        System.out.println(druga.steviloKopij(1828));
        System.out.println(druga.steviloKopij(1827));
        System.out.println(druga.steviloKopij(359));
        System.out.println(druga.steviloKopij(1181));
        System.out.println(druga.steviloKopij(482));
        System.out.println(druga.steviloKopij(1806));
        System.out.println(druga.steviloKopij(650));
        System.out.println(druga.steviloKopij(879));
        System.out.println(druga.steviloKopij(1454));
        System.out.println(druga.steviloKopij(1858));
        System.out.println(druga.steviloKopij(1985));
        System.out.println(druga.steviloKopij(1095));
        System.out.println(druga.steviloKopij(1956));
        System.out.println(druga.steviloKopij(1732));
        System.out.println(druga.steviloKopij(535));
        System.out.println(druga.steviloKopij(1184));
        System.out.println(druga.steviloKopij(1745));
        System.out.println(druga.steviloKopij(118));
        System.out.println(druga.steviloKopij(476));
        System.out.println(druga.steviloKopij(524));
        System.out.println(druga.steviloKopij(1648));
        System.out.println(druga.steviloKopij(946));
        System.out.println(druga.steviloKopij(1169));
        System.out.println(druga.steviloKopij(815));
        System.out.println(druga.steviloKopij(626));
    }
}
