
public class Test06 {

    public static void main(String[] args) {
        Vreca vreca = new Vreca();

        vreca.dodaj("ifx");
        vreca.dodaj("gcay");
        vreca.dodaj("lkt");
        vreca.dodaj("bcyit", 3);
        vreca.dodaj("oami");
        vreca.dodaj("dfot", 5);
        vreca.dodaj("rgy");
        vreca.dodaj("tkkv");
        vreca.dodaj("gpan", 4);
        vreca.dodaj("vts", 5);
        vreca.dodaj("nel", 5);
        vreca.dodaj("abeh", 4);
        vreca.dodaj("ixtk", 2);
        vreca.dodaj("icm", 5);
        vreca.dodaj("fzr", 4);
        vreca.dodaj("bfm", 1);
        vreca.dodaj("rbefy");
        vreca.dodaj("yy");
        vreca.dodaj("svxof");
        vreca.dodaj("gzhj");
        vreca.dodaj("ww");
        vreca.dodaj("pekl");
        vreca.dodaj("l");
        vreca.dodaj("afwvr");
        vreca.dodaj("pgnk");
        vreca.dodaj("tkkv");
        vreca.dodaj("cywfq");
        vreca.dodaj("bdoj");
        vreca.dodaj("vl");
        vreca.dodaj("lkt");
        vreca.dodaj("hecrt");
        vreca.dodaj("ssqt", 3);
        vreca.dodaj("ixtk", 4);
        vreca.dodaj("cmol");
        vreca.dodaj("gcay", 1);
        vreca.dodaj("gcay");
        vreca.dodaj("tkkv", 3);
        vreca.dodaj("crmw");
        vreca.dodaj("fzr");
        vreca.dodaj("mo", 5);
        vreca.dodaj("rs", 4);
        vreca.dodaj("zw", 1);
        vreca.dodaj("phozz", 4);
        vreca.dodaj("rbefy");
        vreca.dodaj("yvx", 1);
        vreca.dodaj("ipv");
        vreca.dodaj("pekl", 5);
        vreca.dodaj("vts");
        vreca.dodaj("qhwox", 5);
        vreca.dodaj("ken");
        vreca.dodaj("whdes", 4);
        vreca.dodaj("afwvr");
        vreca.dodaj("fqn", 1);
        vreca.dodaj("hecrt");
        vreca.dodaj("hpt");
        vreca.dodaj("ipv", 4);
        vreca.dodaj("jyi", 4);
        vreca.dodaj("yzayf", 3);
        vreca.dodaj("ixtk", 5);
        vreca.dodaj("jomoz");
        vreca.dodaj("rxgw");
        vreca.dodaj("cywfq", 1);
        vreca.dodaj("rbefy");
        vreca.dodaj("lzuy", 3);
        vreca.dodaj("ikpwd");
        vreca.dodaj("ezjqx");
        vreca.dodaj("whdes", 5);
        vreca.dodaj("crmw");
        vreca.dodaj("zlui");
        vreca.dodaj("naseg", 5);
        vreca.dodaj("rqmd");
        vreca.dodaj("lzuy");
        vreca.dodaj("ww", 2);
        vreca.dodaj("fqn", 2);
        vreca.dodaj("ixtk");
        vreca.dodaj("timf", 2);
        vreca.dodaj("guoaq");
        vreca.dodaj("naseg");
        vreca.dodaj("bcyit");
        vreca.dodaj("hpt", 1);
        vreca.dodaj("vga", 2);
        vreca.dodaj("gzhj");
        vreca.dodaj("achf");
        vreca.dodaj("yv", 2);
        vreca.dodaj("rgy");
        vreca.dodaj("nmwqd");
        vreca.dodaj("vga", 2);
        vreca.dodaj("ym", 5);
        vreca.dodaj("nel", 4);
        vreca.dodaj("iaihl", 4);
        vreca.dodaj("achf");
        vreca.dodaj("jcs", 5);
        vreca.dodaj("bfm");
        vreca.dodaj("ezjqx");
        vreca.dodaj("rs");
        vreca.dodaj("vts");
        vreca.dodaj("nmwqd");
        vreca.dodaj("ixtk", 3);
        vreca.dodaj("yotc", 3);
        vreca.dodaj("kcrbt", 4);
        vreca.dodaj("tlx", 1);
        vreca.dodaj("zw", 2);
        vreca.dodaj("fjcix");
        vreca.dodaj("rgy");
        vreca.dodaj("hs", 3);
        vreca.dodaj("cqfuj");
        vreca.dodaj("qzc", 1);
        vreca.dodaj("oc", 1);
        vreca.dodaj("dv", 5);
        vreca.dodaj("hecrt");
        vreca.dodaj("oc");
        vreca.dodaj("dunfs");
        vreca.dodaj("qhwox");
        vreca.dodaj("naseg", 2);
        vreca.dodaj("lzuy");
        vreca.dodaj("guoaq");
        vreca.dodaj("ifx");
        vreca.dodaj("rgy");
        vreca.dodaj("yotc", 4);
        vreca.dodaj("pgnk");
        vreca.dodaj("xhif");
        vreca.dodaj("hv");
        vreca.dodaj("tdwm", 1);
        vreca.dodaj("nmwqd", 4);
        vreca.dodaj("qc");
        vreca.dodaj("opm", 4);
        vreca.dodaj("cnhhf");
        vreca.dodaj("ugup");
        vreca.dodaj("ezjqx");
        vreca.dodaj("tdwm");
        vreca.dodaj("vjtxb");
        vreca.dodaj("fqn");
        vreca.dodaj("timf");
        vreca.dodaj("ixtk", 4);
        vreca.dodaj("th", 2);
        vreca.dodaj("pr");
        vreca.dodaj("l");
        vreca.dodaj("vga");
        vreca.dodaj("fzr", 2);
        vreca.dodaj("dooau", 3);
        vreca.dodaj("svxof", 3);
        vreca.dodaj("pork");
        vreca.dodaj("omllc", 2);
        vreca.dodaj("ciqs", 5);
        vreca.dodaj("qg");
        vreca.dodaj("yvx", 2);
        vreca.dodaj("cnny", 1);
        vreca.dodaj("jomoz");
        vreca.dodaj("svxof");
        vreca.dodaj("hecrt");
        vreca.dodaj("ux");
        vreca.dodaj("rgy");
        vreca.dodaj("tvag", 2);
        vreca.dodaj("cqfuj", 4);
        vreca.dodaj("th", 2);
        vreca.dodaj("ciqs", 5);
        vreca.dodaj("gzhj", 2);
        vreca.dodaj("bdoj");
        vreca.dodaj("vga", 4);
        vreca.dodaj("apbpx", 2);
        vreca.dodaj("pork");
        vreca.dodaj("tlx", 4);
        vreca.dodaj("lzuy");
        vreca.dodaj("fqn", 1);
        vreca.dodaj("pgnk", 5);
        vreca.dodaj("ne", 5);
        vreca.dodaj("cnny", 3);
        vreca.dodaj("tkkv");
        vreca.dodaj("upl");
        vreca.dodaj("ww");
        vreca.dodaj("dv", 4);
        vreca.dodaj("zovz", 3);
        vreca.dodaj("zab");
        vreca.dodaj("ixtk");
        vreca.dodaj("ux", 3);
        vreca.dodaj("ssqt", 4);
        vreca.dodaj("jomoz", 4);
        vreca.dodaj("zab");
        vreca.dodaj("zab");
        vreca.dodaj("mgt");
        vreca.dodaj("mo", 1);
        vreca.dodaj("rkmn", 3);
        vreca.dodaj("pr");
        vreca.dodaj("zlw", 4);
        vreca.dodaj("gunbb");
        vreca.dodaj("if", 5);
        vreca.dodaj("gzhj");
        vreca.dodaj("bauw", 1);
        vreca.dodaj("mgt", 4);
        vreca.dodaj("pv");
        vreca.dodaj("iaihl", 5);
        vreca.dodaj("ixtk", 5);
        vreca.dodaj("ifx", 2);
        vreca.dodaj("vga");
        vreca.dodaj("qhwox", 2);
        vreca.dodaj("ctufb", 3);
        vreca.dodaj("xm", 4);
        vreca.dodaj("svxof", 3);
        vreca.dodaj("cdeus");
        vreca.dodaj("qzc", 3);
        vreca.dodaj("yvx");
        vreca.dodaj("oami");
        vreca.dodaj("bfm", 3);
        vreca.dodaj("guoaq", 3);
        vreca.dodaj("cmol", 2);
        vreca.dodaj("bcyit");
        vreca.dodaj("dooau");
        vreca.dodaj("gzhj");
        vreca.dodaj("zab", 4);
        vreca.dodaj("zw");
        vreca.dodaj("zw", 3);
        vreca.dodaj("tppi", 3);
        vreca.dodaj("if", 2);
        vreca.dodaj("svxof");
        vreca.dodaj("hv");
        vreca.dodaj("vfklz", 1);
        vreca.dodaj("dv");
        vreca.dodaj("yotc", 4);
        vreca.dodaj("yy");
        vreca.dodaj("gcay");
        vreca.dodaj("pv");
        vreca.dodaj("pv", 1);
        vreca.dodaj("timf", 1);
        vreca.dodaj("dv");
        vreca.dodaj("bfm", 4);
        vreca.dodaj("rkmn");
        vreca.dodaj("guoaq", 2);
        vreca.dodaj("cnhhf", 1);
        vreca.dodaj("zlw");
        vreca.dodaj("ctufb");
        vreca.dodaj("crmw", 2);
        vreca.dodaj("qzc");
        vreca.dodaj("ww");
        vreca.dodaj("tvag", 3);
        vreca.dodaj("ciqs", 4);
        vreca.dodaj("rxgw", 1);
        vreca.dodaj("zlw");
        vreca.dodaj("hpt");
        vreca.dodaj("icm");
        vreca.dodaj("bauw", 1);
        vreca.dodaj("mslj");
        vreca.dodaj("zw", 5);
        vreca.dodaj("qiul");
        vreca.dodaj("pekl");
        vreca.dodaj("zovz", 2);
        vreca.dodaj("iaihl");
        vreca.dodaj("mgt");
        vreca.dodaj("abeh");
        vreca.dodaj("qc");
        vreca.dodaj("ken", 5);
        vreca.dodaj("pgnk");
        vreca.dodaj("mo");
        vreca.dodaj("l");
        vreca.dodaj("guoaq", 1);
        vreca.dodaj("dv");
        vreca.dodaj("cdeus", 5);
        vreca.dodaj("lskgy");
        vreca.dodaj("oami");
        vreca.dodaj("cdeus");
        vreca.dodaj("tlx", 5);
        vreca.dodaj("dooau", 3);
        vreca.dodaj("erz", 5);
        vreca.dodaj("iaihl");
        vreca.dodaj("pork");

        System.out.println(vreca.steviloRazlicnihElementov());
        System.out.println(vreca.steviloKopij("afwvr"));
        System.out.println(vreca.steviloKopij("fzr"));
        System.out.println(vreca.steviloKopij("vjtxb"));
        System.out.println(vreca.steviloKopij("apbpx"));
        System.out.println(vreca.steviloKopij("dunfs"));
        System.out.println(vreca.steviloKopij("rqmd"));
        System.out.println(vreca.steviloKopij("hpt"));
        System.out.println(vreca.steviloKopij("svxof"));
        System.out.println(vreca.steviloKopij("bdoj"));
        System.out.println(vreca.steviloKopij("tlx"));
        System.out.println(vreca.steviloKopij("oc"));
        System.out.println(vreca.steviloKopij("lkt"));
        System.out.println(vreca.steviloKopij("icm"));
        System.out.println(vreca.steviloKopij("tppi"));
        System.out.println(vreca.steviloKopij("qiul"));
        System.out.println(vreca.steviloKopij("qg"));
        System.out.println(vreca.steviloKopij("ykdmy"));
        System.out.println(vreca.steviloKopij("ssqt"));
        System.out.println(vreca.steviloKopij("if"));
        System.out.println(vreca.steviloKopij("fjcix"));
        System.out.println(vreca.steviloKopij("hv"));
        System.out.println(vreca.steviloKopij("gunbb"));
        System.out.println(vreca.steviloKopij("nel"));
        System.out.println(vreca.steviloKopij("yaetg"));
        System.out.println(vreca.steviloKopij("zw"));
        System.out.println(vreca.steviloKopij("p"));
        System.out.println(vreca.steviloKopij("hecrt"));
        System.out.println(vreca.steviloKopij("upl"));
        System.out.println(vreca.steviloKopij("pork"));
        System.out.println(vreca.steviloKopij("tb"));
        System.out.println(vreca.steviloKopij("yzayf"));
        System.out.println(vreca.steviloKopij("teqkz"));
        System.out.println(vreca.steviloKopij("bfm"));
        System.out.println(vreca.steviloKopij("hs"));
        System.out.println(vreca.steviloKopij("guoaq"));
        System.out.println(vreca.steviloKopij("yotc"));
        System.out.println(vreca.steviloKopij("cdeus"));
        System.out.println(vreca.steviloKopij("jyi"));
        System.out.println(vreca.steviloKopij("xm"));
        System.out.println(vreca.steviloKopij("kcrbt"));
        System.out.println(vreca.steviloKopij("zlui"));
        System.out.println(vreca.steviloKopij("phozz"));
        System.out.println(vreca.steviloKopij("cnhhf"));
        System.out.println(vreca.steviloKopij("zeac"));
        System.out.println(vreca.steviloKopij("zlw"));
        System.out.println(vreca.steviloKopij("cmol"));
        System.out.println(vreca.steviloKopij("qrwe"));
        System.out.println(vreca.steviloKopij("zovz"));
        System.out.println(vreca.steviloKopij("tvag"));
        System.out.println(vreca.steviloKopij("pv"));
        System.out.println(vreca.steviloKopij("whdes"));
        System.out.println(vreca.steviloKopij("crmw"));
        System.out.println(vreca.steviloKopij("lzuy"));
        System.out.println(vreca.steviloKopij("cywfq"));
        System.out.println(vreca.steviloKopij("ctufb"));
        System.out.println(vreca.steviloKopij("tkkv"));
        System.out.println(vreca.steviloKopij("zab"));
        System.out.println(vreca.steviloKopij("qc"));
        System.out.println(vreca.steviloKopij("cnny"));
        System.out.println(vreca.steviloKopij("ux"));
        System.out.println(vreca.steviloKopij("bauw"));
        System.out.println(vreca.steviloKopij("dooau"));
        System.out.println(vreca.steviloKopij("vl"));
        System.out.println(vreca.steviloKopij("l"));
        System.out.println(vreca.steviloKopij("gpan"));
        System.out.println(vreca.steviloKopij("jcs"));
        System.out.println(vreca.steviloKopij("yvx"));
        System.out.println(vreca.steviloKopij("fqn"));
        System.out.println(vreca.steviloKopij("iaihl"));
        System.out.println(vreca.steviloKopij("ds"));
        System.out.println(vreca.steviloKopij("tduar"));
        System.out.println(vreca.steviloKopij("pgnk"));
        System.out.println(vreca.steviloKopij("dv"));
        System.out.println(vreca.steviloKopij("ijr"));
        System.out.println(vreca.steviloKopij("yv"));
        System.out.println(vreca.steviloKopij("qhwox"));
        System.out.println(vreca.steviloKopij("ken"));
        System.out.println(vreca.steviloKopij("onu"));
        System.out.println(vreca.steviloKopij("tdwm"));
        System.out.println(vreca.steviloKopij("bcyit"));
        System.out.println(vreca.steviloKopij("oami"));
        System.out.println(vreca.steviloKopij("qzc"));
        System.out.println(vreca.steviloKopij("tdh"));
        System.out.println(vreca.steviloKopij("rbefy"));
        System.out.println(vreca.steviloKopij("rxgw"));
        System.out.println(vreca.steviloKopij("dfot"));
        System.out.println(vreca.steviloKopij("omllc"));
        System.out.println(vreca.steviloKopij("achf"));
        System.out.println(vreca.steviloKopij("vga"));
        System.out.println(vreca.steviloKopij("col"));
        System.out.println(vreca.steviloKopij("ugup"));
        System.out.println(vreca.steviloKopij("nmwqd"));
        System.out.println(vreca.steviloKopij("mo"));
        System.out.println(vreca.steviloKopij("yy"));
        System.out.println(vreca.steviloKopij("abeh"));
        System.out.println(vreca.steviloKopij("naseg"));
        System.out.println(vreca.steviloKopij("cqfuj"));
        System.out.println(vreca.steviloKopij("gcay"));
        System.out.println(vreca.steviloKopij("i"));
        System.out.println(vreca.steviloKopij("gzhj"));
        System.out.println(vreca.steviloKopij("yvvbh"));
        System.out.println(vreca.steviloKopij("lskgy"));
        System.out.println(vreca.steviloKopij("rkmn"));
        System.out.println(vreca.steviloKopij("vfklz"));
        System.out.println(vreca.steviloKopij("th"));
        System.out.println(vreca.steviloKopij("ne"));
        System.out.println(vreca.steviloKopij("mgt"));
        System.out.println(vreca.steviloKopij("xhif"));
        System.out.println(vreca.steviloKopij("ww"));
        System.out.println(vreca.steviloKopij("mslj"));
        System.out.println(vreca.steviloKopij("ixtk"));
        System.out.println(vreca.steviloKopij("veglo"));
        System.out.println(vreca.steviloKopij("iq"));
        System.out.println(vreca.steviloKopij("pekl"));
        System.out.println(vreca.steviloKopij("erz"));
        System.out.println(vreca.steviloKopij("pr"));
        System.out.println(vreca.steviloKopij("xsqp"));
        System.out.println(vreca.steviloKopij("udk"));
        System.out.println(vreca.steviloKopij("timf"));
        System.out.println(vreca.steviloKopij("rgy"));
        System.out.println(vreca.steviloKopij("ym"));
        System.out.println(vreca.steviloKopij("jomoz"));
        System.out.println(vreca.steviloKopij("ifx"));
        System.out.println(vreca.steviloKopij("ciqs"));
        System.out.println(vreca.steviloKopij("ezjqx"));
        System.out.println(vreca.steviloKopij("ikpwd"));
        System.out.println(vreca.steviloKopij("tttnr"));
        System.out.println(vreca.steviloKopij("vts"));
        System.out.println(vreca.steviloKopij("ipv"));
        System.out.println(vreca.steviloKopij("jpi"));
        System.out.println(vreca.steviloKopij("rs"));
        System.out.println(vreca.steviloKopij("opm"));
    }
}
