
public class Test18 {

    public static void main(String[] args) {
        Vreca vreca = new Vreca();

        vreca.dodaj("yhex");
        vreca.dodaj("bzeya", 47);
        vreca.dodaj("xom", 37);
        vreca.dodaj("mcu", 4);
        vreca.dodaj("uer");
        vreca.dodaj("eym");
        vreca.dodaj("bfm");
        vreca.dodaj("mcu", 84);
        vreca.dodaj("syy");
        vreca.dodaj("aalvk", 58);
        vreca.dodaj("az");
        vreca.dodaj("cjye", 85);
        vreca.dodaj("az");
        vreca.dodaj("mcu");
        vreca.dodaj("xvci");
        vreca.dodaj("syy");
        vreca.dodaj("ne");
        vreca.dodaj("er");
        vreca.dodaj("mcu", 1);
        vreca.dodaj("teeqw");
        vreca.dodaj("ibr", 100);
        vreca.dodaj("mji", 66);
        vreca.dodaj("m", 21);
        vreca.dodaj("bllux");
        vreca.dodaj("vcg", 54);
        vreca.dodaj("xxpa", 9);
        vreca.dodaj("xvci");
        vreca.dodaj("ibr");
        vreca.dodaj("k");
        vreca.dodaj("yhex");
        vreca.dodaj("xom", 45);
        vreca.dodaj("uvfbp");
        vreca.dodaj("bzeya");
        vreca.dodaj("ibr");
        vreca.dodaj("slb");
        vreca.dodaj("pzeei", 64);
        vreca.dodaj("uvfbp", 28);
        vreca.dodaj("bb", 36);
        vreca.dodaj("waa");
        vreca.dodaj("aalvk");
        vreca.dodaj("m", 92);
        vreca.dodaj("bt", 52);
        vreca.dodaj("tkkv");
        vreca.dodaj("pgd");
        vreca.dodaj("hdeqb", 7);
        vreca.dodaj("uer", 68);
        vreca.dodaj("scony");
        vreca.dodaj("xkvfl", 4);
        vreca.dodaj("jup");
        vreca.dodaj("dyuk");
        vreca.dodaj("kit", 31);
        vreca.dodaj("xom");
        vreca.dodaj("sddvk", 50);
        vreca.dodaj("scony", 93);
        vreca.dodaj("uer");
        vreca.dodaj("cxbwv", 86);
        vreca.dodaj("lkt", 26);
        vreca.dodaj("uvfbp");
        vreca.dodaj("m", 100);
        vreca.dodaj("cxbwv", 47);
        vreca.dodaj("er");
        vreca.dodaj("knzy", 35);
        vreca.dodaj("cxbwv");
        vreca.dodaj("jdjvw", 47);
        vreca.dodaj("hxz", 94);
        vreca.dodaj("thjv");
        vreca.dodaj("og", 24);
        vreca.dodaj("pbl", 46);
        vreca.dodaj("yvvbh");
        vreca.dodaj("aalvk", 2);
        vreca.dodaj("hht", 8);
        vreca.dodaj("vcumk", 48);
        vreca.dodaj("dyuk");
        vreca.dodaj("veglo", 28);
        vreca.dodaj("cjye");
        vreca.dodaj("syy", 96);
        vreca.dodaj("rllh");
        vreca.dodaj("mhvj", 1);
        vreca.dodaj("az", 31);
        vreca.dodaj("jdjvw");
        vreca.dodaj("mhvj");
        vreca.dodaj("bt");
        vreca.dodaj("lkt", 87);
        vreca.dodaj("veglo");
        vreca.dodaj("ofgkp");
        vreca.dodaj("ux");
        vreca.dodaj("slb", 59);
        vreca.dodaj("bfvzn");
        vreca.dodaj("vcumk");
        vreca.dodaj("xvci");
        vreca.dodaj("acg");
        vreca.dodaj("mcu");
        vreca.dodaj("tkhf");
        vreca.dodaj("uzl", 75);
        vreca.dodaj("rainm");
        vreca.dodaj("tkhf", 49);
        vreca.dodaj("k");
        vreca.dodaj("yxnb", 81);
        vreca.dodaj("rainm", 17);
        vreca.dodaj("mji", 66);
        vreca.dodaj("tkkv");
        vreca.dodaj("pbl", 85);
        vreca.dodaj("ux", 100);
        vreca.dodaj("ofgkp");
        vreca.dodaj("dyuk", 20);
        vreca.dodaj("bllux");
        vreca.dodaj("xxpa");
        vreca.dodaj("hht", 15);
        vreca.dodaj("thjv");
        vreca.dodaj("lkt");
        vreca.dodaj("jdjvw");
        vreca.dodaj("bfm");
        vreca.dodaj("xpg");
        vreca.dodaj("waa");
        vreca.dodaj("m", 88);
        vreca.dodaj("rllh");
        vreca.dodaj("teeqw");
        vreca.dodaj("bzeya");
        vreca.dodaj("bb", 39);
        vreca.dodaj("pbl");
        vreca.dodaj("az");
        vreca.dodaj("eym");
        vreca.dodaj("mhvj");
        vreca.dodaj("yxnb");
        vreca.dodaj("knzy", 41);
        vreca.dodaj("wcfor");
        vreca.dodaj("cxbwv");
        vreca.dodaj("dyuk");
        vreca.dodaj("tkhf", 43);
        vreca.dodaj("bllux");
        vreca.dodaj("og", 61);
        vreca.dodaj("yxnb", 92);
        vreca.dodaj("mcu");
        vreca.dodaj("sddvk", 7);
        vreca.dodaj("ofgkp");
        vreca.dodaj("yhex", 52);
        vreca.dodaj("ofgkp");
        vreca.dodaj("sddvk", 77);
        vreca.dodaj("eym");
        vreca.dodaj("m");
        vreca.dodaj("bzeya");
        vreca.dodaj("mcu", 51);
        vreca.dodaj("ulh");
        vreca.dodaj("vcumk", 41);

        vreca.odstrani("dyuk", 88);
        vreca.odstrani("syy");
        vreca.odstrani("er");
        vreca.odstrani("hxz");
        vreca.odstrani("ne");
        vreca.odstrani("ulh");
        vreca.odstrani("jdjvw", 34);
        vreca.odstrani("tkhf", 97);
        vreca.odstrani("thjv");
        vreca.odstrani("wylz");
        vreca.odstrani("knzy", 60);
        vreca.odstrani("sddvk", 74);
        vreca.odstrani("pgd", 46);
        vreca.odstrani("mji");
        vreca.odstrani("cmol");
        vreca.odstrani("aalvk");
        vreca.odstrani("vcg");
        vreca.odstrani("bllux", 53);
        vreca.odstrani("m");
        vreca.odstrani("cxbwv", 10);
        vreca.odstrani("uvl", 46);
        vreca.odstrani("hdeqb");
        vreca.odstrani("xom");
        vreca.odstrani("teeqw");
        vreca.odstrani("uvfbp");
        vreca.odstrani("bzeya");
        vreca.odstrani("bb", 22);
        vreca.odstrani("jup", 83);
        vreca.odstrani("pbl");
        vreca.odstrani("yvvbh");
        vreca.odstrani("bfvzn", 11);
        vreca.odstrani("cjye");
        vreca.odstrani("kit");
        vreca.odstrani("xvci", 52);
        vreca.odstrani("xpg");
        vreca.odstrani("ofgkp", 41);
        vreca.odstrani("bfm");
        vreca.odstrani("az", 29);
        vreca.odstrani("bt", 57);
        vreca.odstrani("yi", 69);
        vreca.odstrani("yhex");
        vreca.odstrani("mhvj");
        vreca.odstrani("bgvp", 90);
        vreca.odstrani("hkboo");
        vreca.odstrani("wcfor");
        vreca.odstrani("tkkv");
        vreca.odstrani("hht");
        vreca.odstrani("rllh");
        vreca.odstrani("mcu", 14);
        vreca.odstrani("rainm", 57);
        vreca.odstrani("lkt", 86);

        System.out.println(vreca.steviloRazlicnihElementov());
        System.out.println(vreca.steviloKopij("bzeya"));
        System.out.println(vreca.steviloKopij("sddvk"));
        System.out.println(vreca.steviloKopij("xkvfl"));
        System.out.println(vreca.steviloKopij("thjv"));
        System.out.println(vreca.steviloKopij("eym"));
        System.out.println(vreca.steviloKopij("jup"));
        System.out.println(vreca.steviloKopij("onofb"));
        System.out.println(vreca.steviloKopij("m"));
        System.out.println(vreca.steviloKopij("er"));
        System.out.println(vreca.steviloKopij("wylz"));
        System.out.println(vreca.steviloKopij("cxbwv"));
        System.out.println(vreca.steviloKopij("az"));
        System.out.println(vreca.steviloKopij("mji"));
        System.out.println(vreca.steviloKopij("kit"));
        System.out.println(vreca.steviloKopij("xom"));
        System.out.println(vreca.steviloKopij("bt"));
        System.out.println(vreca.steviloKopij("hxz"));
        System.out.println(vreca.steviloKopij("uzl"));
        System.out.println(vreca.steviloKopij("syy"));
        System.out.println(vreca.steviloKopij("jdjvw"));
        System.out.println(vreca.steviloKopij("bpqij"));
        System.out.println(vreca.steviloKopij("k"));
        System.out.println(vreca.steviloKopij("uvfbp"));
        System.out.println(vreca.steviloKopij("pgd"));
        System.out.println(vreca.steviloKopij("cmol"));
        System.out.println(vreca.steviloKopij("rllh"));
        System.out.println(vreca.steviloKopij("pzeei"));
        System.out.println(vreca.steviloKopij("tkkv"));
        System.out.println(vreca.steviloKopij("hht"));
        System.out.println(vreca.steviloKopij("hkboo"));
        System.out.println(vreca.steviloKopij("veglo"));
        System.out.println(vreca.steviloKopij("bllux"));
        System.out.println(vreca.steviloKopij("ne"));
        System.out.println(vreca.steviloKopij("xxpa"));
        System.out.println(vreca.steviloKopij("slb"));
        System.out.println(vreca.steviloKopij("xvci"));
        System.out.println(vreca.steviloKopij("xpg"));
        System.out.println(vreca.steviloKopij("hdeqb"));
        System.out.println(vreca.steviloKopij("mcu"));
        System.out.println(vreca.steviloKopij("mhvj"));
        System.out.println(vreca.steviloKopij("uvl"));
        System.out.println(vreca.steviloKopij("og"));
        System.out.println(vreca.steviloKopij("bfvzn"));
        System.out.println(vreca.steviloKopij("ibr"));
        System.out.println(vreca.steviloKopij("ulh"));
        System.out.println(vreca.steviloKopij("tkhf"));
        System.out.println(vreca.steviloKopij("teeqw"));
        System.out.println(vreca.steviloKopij("knzy"));
        System.out.println(vreca.steviloKopij("aalvk"));
        System.out.println(vreca.steviloKopij("waa"));
        System.out.println(vreca.steviloKopij("tr"));
        System.out.println(vreca.steviloKopij("bgvp"));
        System.out.println(vreca.steviloKopij("bb"));
        System.out.println(vreca.steviloKopij("yxnb"));
        System.out.println(vreca.steviloKopij("cjye"));
        System.out.println(vreca.steviloKopij("uer"));
        System.out.println(vreca.steviloKopij("yhex"));
        System.out.println(vreca.steviloKopij("dyuk"));
        System.out.println(vreca.steviloKopij("yvvbh"));
        System.out.println(vreca.steviloKopij("vcumk"));
        System.out.println(vreca.steviloKopij("yi"));
        System.out.println(vreca.steviloKopij("ux"));
        System.out.println(vreca.steviloKopij("pbl"));
        System.out.println(vreca.steviloKopij("lkt"));
        System.out.println(vreca.steviloKopij("vcg"));
        System.out.println(vreca.steviloKopij("scony"));
        System.out.println(vreca.steviloKopij("ofgkp"));
        System.out.println(vreca.steviloKopij("acg"));
        System.out.println(vreca.steviloKopij("rainm"));
        System.out.println(vreca.steviloKopij("lkagg"));
        System.out.println(vreca.steviloKopij("bfm"));
        System.out.println(vreca.steviloKopij("wcfor"));
    }
}
