// _NE_ODSTRANI_

import java.awt.*;

public class Test10 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaNavpicno(8, 7, 10),
            new Tretja.LadjaVodoravno(0, 0, 19),
            new Tretja.LadjaVodoravno(2, 14, 5),
            new Tretja.LadjaNavpicno(10, 14, 7),
            new Tretja.LadjaVodoravno(2, 5, 7),
            new Tretja.LadjaVodoravno(8, 10, 4),
            new Tretja.LadjaVodoravno(5, 12, 7),
            new Tretja.LadjaVodoravno(18, 10, 9),
            new Tretja.LadjaNavpicno(3, 2, 17),
            new Tretja.LadjaVodoravno(11, 9, 4),
            new Tretja.LadjaNavpicno(10, 0, 2),
            new Tretja.LadjaNavpicno(4, 4, 7),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(12, 4),
            new Tretja.Strel(10, 2),
            new Tretja.Strel(4, 7),
            new Tretja.Strel(12, 6),
            new Tretja.Strel(5, 9),
            new Tretja.Strel(9, 14),
            new Tretja.Strel(6, 1),
            new Tretja.Strel(9, 12),
            new Tretja.Strel(2, 11),
            new Tretja.Strel(17, 10),
            new Tretja.Strel(10, 3),
            new Tretja.Strel(19, 2),
            new Tretja.Strel(5, 13),
            new Tretja.Strel(4, 16),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(9, 7),
            new Tretja.Strel(11, 0),
            new Tretja.Strel(11, 3),
            new Tretja.Strel(12, 16),
            new Tretja.Strel(15, 10),
            new Tretja.Strel(10, 1),
            new Tretja.Strel(11, 18),
            new Tretja.Strel(13, 17),
            new Tretja.Strel(18, 18),
            new Tretja.Strel(8, 9),
            new Tretja.Strel(13, 6),
            new Tretja.Strel(12, 2),
            new Tretja.Strel(19, 13),
            new Tretja.Strel(2, 19),
            new Tretja.Strel(9, 8),
            new Tretja.Strel(15, 3),
            new Tretja.Strel(5, 8),
            new Tretja.Strel(10, 4),
            new Tretja.Strel(19, 10),
            new Tretja.Strel(19, 9),
            new Tretja.Strel(1, 7),
            new Tretja.Strel(18, 16),
            new Tretja.Strel(11, 8),
            new Tretja.Strel(3, 11),
            new Tretja.Strel(1, 4),
            new Tretja.Strel(1, 19),
            new Tretja.Strel(19, 7),
            new Tretja.Strel(2, 7),
            new Tretja.Strel(12, 8),
            new Tretja.Strel(15, 19),
            new Tretja.Strel(0, 1),
            new Tretja.Strel(8, 16),
            new Tretja.Strel(0, 15),
            new Tretja.Strel(4, 3),
            new Tretja.Strel(9, 6),
            new Tretja.Strel(2, 4),
            new Tretja.Strel(7, 15),
            new Tretja.Strel(3, 16),
            new Tretja.Strel(6, 19),
            new Tretja.Strel(12, 7),
            new Tretja.Strel(3, 5),
            new Tretja.Strel(19, 14),
            new Tretja.Strel(17, 15),
            new Tretja.Strel(9, 10),
            new Tretja.Strel(18, 11),
            new Tretja.Strel(1, 14),
            new Tretja.Strel(13, 18),
            new Tretja.Strel(1, 6),
            new Tretja.Strel(5, 1),
            new Tretja.Strel(4, 12),
            new Tretja.Strel(4, 9),
            new Tretja.Strel(3, 8),
            new Tretja.Strel(0, 13),
            new Tretja.Strel(17, 5),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(8, 2),
            new Tretja.Strel(14, 4),
            new Tretja.Strel(1, 12),
            new Tretja.Strel(13, 15),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(17, 8),
            new Tretja.Strel(0, 12),
            new Tretja.Strel(2, 1),
            new Tretja.Strel(4, 19),
            new Tretja.Strel(17, 1),
            new Tretja.Strel(6, 7),
            new Tretja.Strel(0, 6),
            new Tretja.Strel(13, 16),
            new Tretja.Strel(19, 5),
            new Tretja.Strel(8, 4),
            new Tretja.Strel(16, 11),
            new Tretja.Strel(6, 4),
            new Tretja.Strel(2, 8),
            new Tretja.Strel(18, 0),
            new Tretja.Strel(16, 12),
            new Tretja.Strel(6, 10),
            new Tretja.Strel(12, 18),
            new Tretja.Strel(10, 17),
            new Tretja.Strel(1, 0),
            new Tretja.Strel(8, 15),
            new Tretja.Strel(7, 3),
            new Tretja.Strel(8, 19),
            new Tretja.Strel(13, 11),
            new Tretja.Strel(16, 13),
            new Tretja.Strel(5, 2),
            new Tretja.Strel(7, 0),
            new Tretja.Strel(16, 14),
            new Tretja.Strel(15, 7),
            new Tretja.Strel(18, 19),
            new Tretja.Strel(2, 2),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(5, 7),
            new Tretja.Strel(18, 12),
            new Tretja.Strel(7, 18),
            new Tretja.Strel(5, 0),
            new Tretja.Strel(6, 5),
            new Tretja.Strel(15, 9),
            new Tretja.Strel(15, 15),
            new Tretja.Strel(2, 10),
            new Tretja.Strel(15, 0),
            new Tretja.Strel(10, 9),
            new Tretja.Strel(19, 12),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(12, 5),
            new Tretja.Strel(9, 2),
            new Tretja.Strel(1, 8),
            new Tretja.Strel(7, 6),
            new Tretja.Strel(19, 17),
            new Tretja.Strel(5, 3),
            new Tretja.Strel(4, 6),
            new Tretja.Strel(5, 14),
            new Tretja.Strel(16, 2),
            new Tretja.Strel(15, 13),
            new Tretja.Strel(0, 5),
            new Tretja.Strel(4, 14),
            new Tretja.Strel(1, 3),
            new Tretja.Strel(0, 4),
            new Tretja.Strel(10, 19),
            new Tretja.Strel(11, 11),
            new Tretja.Strel(6, 18),
            new Tretja.Strel(13, 2),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(11, 16),
            new Tretja.Strel(19, 18),
            new Tretja.Strel(17, 16),
            new Tretja.Strel(6, 13),
            new Tretja.Strel(14, 14),
            new Tretja.Strel(19, 16),
            new Tretja.Strel(5, 5),
            new Tretja.Strel(12, 9),
            new Tretja.Strel(18, 2),
            new Tretja.Strel(13, 10),
            new Tretja.Strel(9, 5),
        };

        Tretja tretja = new Tretja(20, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat10.png", "720x600"}, "Potapljanje ladjic");
    }
}
