
import java.util.Arrays;

public class Test45 {

    public static void main(String[] args) {
        Druga.Oseba oseba1 = new Druga.Oseba("Karel Debeljak");
        Druga.Oseba[] osebaa1 = {oseba1};
        Druga.Clanek[] clanki1 = {
            new Druga.Clanek("A", osebaa1, 18),
            new Druga.Clanek("A", osebaa1, 10),
            new Druga.Clanek("A", osebaa1, 4),
            new Druga.Clanek("A", osebaa1, 21),
            new Druga.Clanek("A", osebaa1, 6),
            new Druga.Clanek("A", osebaa1, 27),
            new Druga.Clanek("A", osebaa1, 2),
            new Druga.Clanek("A", osebaa1, 12),
            new Druga.Clanek("A", osebaa1, 13),
            new Druga.Clanek("A", osebaa1, 0),
            new Druga.Clanek("A", osebaa1, 5),
            new Druga.Clanek("A", osebaa1, 14),
            new Druga.Clanek("A", osebaa1, 21),
            new Druga.Clanek("A", osebaa1, 1),
            new Druga.Clanek("A", osebaa1, 16),
            new Druga.Clanek("A", osebaa1, 26),
            new Druga.Clanek("A", osebaa1, 25),
            new Druga.Clanek("A", osebaa1, 9),
            new Druga.Clanek("A", osebaa1, 1),
            new Druga.Clanek("A", osebaa1, 10),
            new Druga.Clanek("A", osebaa1, 7),
            new Druga.Clanek("A", osebaa1, 28),
            new Druga.Clanek("A", osebaa1, 24),
            new Druga.Clanek("A", osebaa1, 5),
            new Druga.Clanek("A", osebaa1, 6),
            new Druga.Clanek("A", osebaa1, 7),
            new Druga.Clanek("A", osebaa1, 23),
            new Druga.Clanek("A", osebaa1, 29),
            new Druga.Clanek("A", osebaa1, 1),
            new Druga.Clanek("A", osebaa1, 7),
            new Druga.Clanek("A", osebaa1, 24),
            new Druga.Clanek("A", osebaa1, 23),
            new Druga.Clanek("A", osebaa1, 11),
            new Druga.Clanek("A", osebaa1, 27),
            new Druga.Clanek("A", osebaa1, 30),
            new Druga.Clanek("A", osebaa1, 18),
            new Druga.Clanek("A", osebaa1, 24),
            new Druga.Clanek("A", osebaa1, 22),
            new Druga.Clanek("A", osebaa1, 15),
            new Druga.Clanek("A", osebaa1, 16),
            new Druga.Clanek("A", osebaa1, 7),
            new Druga.Clanek("A", osebaa1, 10),
            new Druga.Clanek("A", osebaa1, 23),
            new Druga.Clanek("A", osebaa1, 5),
            new Druga.Clanek("A", osebaa1, 12),
            new Druga.Clanek("A", osebaa1, 12),
            new Druga.Clanek("A", osebaa1, 23),
            new Druga.Clanek("A", osebaa1, 21),
            new Druga.Clanek("A", osebaa1, 2),
            new Druga.Clanek("A", osebaa1, 15),
            new Druga.Clanek("A", osebaa1, 0),
            new Druga.Clanek("A", osebaa1, 12),
            new Druga.Clanek("A", osebaa1, 1),
            new Druga.Clanek("A", osebaa1, 22),
            new Druga.Clanek("A", osebaa1, 10),
            new Druga.Clanek("A", osebaa1, 5),
            new Druga.Clanek("A", osebaa1, 6),
            new Druga.Clanek("A", osebaa1, 7),
            new Druga.Clanek("A", osebaa1, 19),
            new Druga.Clanek("A", osebaa1, 20),
        };
        oseba1.nastaviClanke(clanki1);
        System.out.println(oseba1.hIndeks());

        Druga.Oseba oseba2 = new Druga.Oseba("Peter Urh");
        Druga.Oseba[] osebaa2 = {oseba2};
        Druga.Clanek[] clanki2 = {
            new Druga.Clanek("A", osebaa2, 7),
            new Druga.Clanek("A", osebaa2, 22),
            new Druga.Clanek("A", osebaa2, 16),
            new Druga.Clanek("A", osebaa2, 9),
            new Druga.Clanek("A", osebaa2, 13),
            new Druga.Clanek("A", osebaa2, 10),
            new Druga.Clanek("A", osebaa2, 23),
            new Druga.Clanek("A", osebaa2, 6),
            new Druga.Clanek("A", osebaa2, 27),
            new Druga.Clanek("A", osebaa2, 20),
            new Druga.Clanek("A", osebaa2, 8),
            new Druga.Clanek("A", osebaa2, 12),
            new Druga.Clanek("A", osebaa2, 22),
            new Druga.Clanek("A", osebaa2, 15),
            new Druga.Clanek("A", osebaa2, 6),
            new Druga.Clanek("A", osebaa2, 13),
            new Druga.Clanek("A", osebaa2, 12),
            new Druga.Clanek("A", osebaa2, 8),
            new Druga.Clanek("A", osebaa2, 0),
            new Druga.Clanek("A", osebaa2, 7),
            new Druga.Clanek("A", osebaa2, 20),
            new Druga.Clanek("A", osebaa2, 11),
            new Druga.Clanek("A", osebaa2, 27),
            new Druga.Clanek("A", osebaa2, 7),
            new Druga.Clanek("A", osebaa2, 12),
            new Druga.Clanek("A", osebaa2, 14),
            new Druga.Clanek("A", osebaa2, 21),
            new Druga.Clanek("A", osebaa2, 16),
            new Druga.Clanek("A", osebaa2, 1),
            new Druga.Clanek("A", osebaa2, 28),
            new Druga.Clanek("A", osebaa2, 30),
            new Druga.Clanek("A", osebaa2, 5),
            new Druga.Clanek("A", osebaa2, 14),
            new Druga.Clanek("A", osebaa2, 2),
            new Druga.Clanek("A", osebaa2, 14),
            new Druga.Clanek("A", osebaa2, 15),
            new Druga.Clanek("A", osebaa2, 29),
            new Druga.Clanek("A", osebaa2, 4),
            new Druga.Clanek("A", osebaa2, 17),
            new Druga.Clanek("A", osebaa2, 7),
            new Druga.Clanek("A", osebaa2, 10),
            new Druga.Clanek("A", osebaa2, 28),
            new Druga.Clanek("A", osebaa2, 21),
            new Druga.Clanek("A", osebaa2, 15),
            new Druga.Clanek("A", osebaa2, 9),
            new Druga.Clanek("A", osebaa2, 30),
            new Druga.Clanek("A", osebaa2, 6),
            new Druga.Clanek("A", osebaa2, 17),
            new Druga.Clanek("A", osebaa2, 19),
            new Druga.Clanek("A", osebaa2, 12),
            new Druga.Clanek("A", osebaa2, 30),
            new Druga.Clanek("A", osebaa2, 0),
            new Druga.Clanek("A", osebaa2, 0),
            new Druga.Clanek("A", osebaa2, 27),
            new Druga.Clanek("A", osebaa2, 13),
            new Druga.Clanek("A", osebaa2, 11),
            new Druga.Clanek("A", osebaa2, 29),
            new Druga.Clanek("A", osebaa2, 28),
            new Druga.Clanek("A", osebaa2, 13),
            new Druga.Clanek("A", osebaa2, 25),
        };
        oseba2.nastaviClanke(clanki2);
        System.out.println(oseba2.hIndeks());

        Druga.Oseba oseba3 = new Druga.Oseba("Vinko Satler");
        Druga.Oseba[] osebaa3 = {oseba3};
        Druga.Clanek[] clanki3 = {
            new Druga.Clanek("A", osebaa3, 17),
            new Druga.Clanek("A", osebaa3, 17),
            new Druga.Clanek("A", osebaa3, 23),
            new Druga.Clanek("A", osebaa3, 13),
            new Druga.Clanek("A", osebaa3, 5),
            new Druga.Clanek("A", osebaa3, 26),
            new Druga.Clanek("A", osebaa3, 21),
            new Druga.Clanek("A", osebaa3, 29),
            new Druga.Clanek("A", osebaa3, 26),
            new Druga.Clanek("A", osebaa3, 22),
            new Druga.Clanek("A", osebaa3, 29),
            new Druga.Clanek("A", osebaa3, 26),
            new Druga.Clanek("A", osebaa3, 5),
            new Druga.Clanek("A", osebaa3, 27),
            new Druga.Clanek("A", osebaa3, 4),
            new Druga.Clanek("A", osebaa3, 8),
            new Druga.Clanek("A", osebaa3, 9),
            new Druga.Clanek("A", osebaa3, 29),
            new Druga.Clanek("A", osebaa3, 24),
            new Druga.Clanek("A", osebaa3, 8),
            new Druga.Clanek("A", osebaa3, 21),
            new Druga.Clanek("A", osebaa3, 11),
            new Druga.Clanek("A", osebaa3, 6),
            new Druga.Clanek("A", osebaa3, 24),
            new Druga.Clanek("A", osebaa3, 28),
            new Druga.Clanek("A", osebaa3, 13),
            new Druga.Clanek("A", osebaa3, 22),
            new Druga.Clanek("A", osebaa3, 19),
            new Druga.Clanek("A", osebaa3, 22),
            new Druga.Clanek("A", osebaa3, 3),
            new Druga.Clanek("A", osebaa3, 16),
            new Druga.Clanek("A", osebaa3, 11),
            new Druga.Clanek("A", osebaa3, 20),
            new Druga.Clanek("A", osebaa3, 20),
            new Druga.Clanek("A", osebaa3, 7),
            new Druga.Clanek("A", osebaa3, 30),
            new Druga.Clanek("A", osebaa3, 28),
            new Druga.Clanek("A", osebaa3, 25),
            new Druga.Clanek("A", osebaa3, 8),
            new Druga.Clanek("A", osebaa3, 4),
            new Druga.Clanek("A", osebaa3, 16),
            new Druga.Clanek("A", osebaa3, 5),
            new Druga.Clanek("A", osebaa3, 8),
            new Druga.Clanek("A", osebaa3, 26),
            new Druga.Clanek("A", osebaa3, 4),
            new Druga.Clanek("A", osebaa3, 10),
            new Druga.Clanek("A", osebaa3, 27),
            new Druga.Clanek("A", osebaa3, 27),
            new Druga.Clanek("A", osebaa3, 13),
            new Druga.Clanek("A", osebaa3, 15),
            new Druga.Clanek("A", osebaa3, 2),
            new Druga.Clanek("A", osebaa3, 4),
            new Druga.Clanek("A", osebaa3, 22),
            new Druga.Clanek("A", osebaa3, 3),
            new Druga.Clanek("A", osebaa3, 18),
            new Druga.Clanek("A", osebaa3, 15),
            new Druga.Clanek("A", osebaa3, 22),
            new Druga.Clanek("A", osebaa3, 25),
            new Druga.Clanek("A", osebaa3, 5),
            new Druga.Clanek("A", osebaa3, 6),
        };
        oseba3.nastaviClanke(clanki3);
        System.out.println(oseba3.hIndeks());

    }
}
