
public class Test50 {

    private static final boolean T = true;
    private static final boolean F = false;

    private static boolean[][] TABELA01 = {
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F},
        {F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, T, F, F, F, F, F},
        {F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F},
        {F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F},
        {F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F},
        {F, T, F, F, F, F, F, F, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, T, T, F, F, F, T, F, T, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, T, F, F, F},
        {T, F, T, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, T, F, F, F, T, F, T, T, F, F, F, F, T, F, T, F, F},
        {F, F, F, T, T, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, T, F, F, T, F, T, F, F, F, T, F, F, F, T, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, T},
        {T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F, F, F, T, T, T, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, T, T, F, T, F, T, F, F, F, F},
        {F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, T, T, T, F, F, F, F, F, F, F, F, T, F, T, T, T, T, F, F, T, F, F, T, F, F, F},
        {T, F, F, T, T, T, F, F, T, F, F, F, T, F, F, T, F, F, T, F, F, T, F, F, F, F, T, F, F, F, F, T, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, T},
        {F, F, T, F, T, F, F, F, F, F, F, T, F, F, F, F, T, T, F, F, T, F, F, F, T, F, F, F, F, T, F, T, T, T, T, F, F, F, F, F, F, T, T, F, F, T, F, F, F, F, T, T},
        {F, F, F, F, T, T, T, T, F, T, T, F, F, T, F, F, F, F, F, F, F, F, T, T, F, F, T, F, F, F, F, F, F, T, F, F, F, F, T, T, T, T, T, F, F, T, F, F, F, F, F, T},
        {T, F, F, T, F, F, F, T, F, T, F, T, F, F, T, T, F, F, F, F, T, F, T, F, F, T, T, F, T, F, T, F, F, F, F, F, F, F, T, F, T, T, F, T, T, F, F, F, F, T, F, F},
        {F, T, T, F, T, F, F, T, F, T, T, F, F, T, T, T, F, F, T, F, F, T, F, F, F, T, F, F, F, F, F, F, T, T, T, F, F, F, F, F, F, F, T, T, F, T, F, T, T, F, F, F},
        {T, T, F, T, F, F, F, F, T, F, F, F, T, F, T, T, F, T, T, F, T, F, T, T, T, F, F, T, T, F, F, F, F, F, T, T, F, T, F, T, F, F, T, F, F, F, F, F, F, F, T, F},
        {T, T, F, F, F, T, F, F, T, T, F, T, F, F, F, F, F, T, F, T, F, F, F, T, T, T, F, T, T, F, T, F, F, F, T, T, T, T, T, F, F, F, T, F, F, T, T, F, F, T, F, F},
        {F, T, F, F, T, T, T, F, T, F, T, F, F, F, T, T, F, F, T, T, F, F, T, F, T, T, T, F, T, T, T, F, F, F, T, F, T, T, F, F, T, F, F, F, T, T, F, F, F, F, F, T},
        {T, T, F, F, F, F, F, F, T, T, F, T, T, F, T, T, F, F, T, F, F, F, T, T, T, F, F, F, T, T, F, T, F, T, F, T, F, F, T, T, T, T, T, F, F, T, F, F, F, T, T, F},
        {F, F, T, F, F, T, F, F, F, T, T, T, T, T, T, F, F, T, F, T, T, F, F, T, T, F, T, T, F, F, T, F, F, T, T, T, F, F, F, T, F, T, F, T, F, T, T, F, F, T, T, T},
        {F, F, F, T, T, F, T, T, F, T, T, T, T, T, F, T, T, F, T, T, T, T, F, T, T, F, F, T, F, F, T, T, F, F, F, F, T, F, T, F, T, T, T, T, F, T, F, F, T, F, T, F},
        {F, T, T, T, T, F, T, T, T, T, F, F, F, F, T, T, T, T, T, F, T, T, F, T, F, T, F, T, F, F, T, T, T, T, T, F, F, F, F, T, T, F, F, T, F, F, T, T, T, T, F, T},
        {T, T, F, F, T, T, F, T, T, T, T, F, F, F, T, T, T, F, F, T, F, F, T, T, F, T, T, T, F, F, F, T, T, T, F, T, F, T, T, F, F, T, F, T, T, T, F, T, T, T, T, T},
        {F, T, F, T, F, T, T, T, F, T, T, T, F, T, F, T, F, F, T, T, T, T, F, T, F, T, T, T, T, T, F, F, F, T, T, F, F, F, F, T, T, T, T, T, T, T, F, T, T, F, T, T},
        {F, T, T, F, T, F, F, T, F, T, F, T, T, T, F, T, T, T, T, T, T, T, F, T, T, F, F, T, T, T, T, T, F, F, F, F, T, T, T, T, F, T, T, T, T, F, T, T, T, T, T, F},
        {F, T, F, T, T, F, T, F, F, T, T, F, T, T, F, F, T, T, T, T, T, T, F, T, F, T, T, T, F, T, F, T, T, F, T, T, T, T, T, F, T, T, T, F, T, T, T, T, T, T, F, T},
        {T, T, F, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, F, T, T, F, T, T, T, F, T, T, T, F, F, T, T, T, T, T, F, T, T, F, F, T, F, T, T, F},
        {T, T, F, T, T, F, T, F, F, F, T, T, T, T, T, F, F, T, F, T, T, T, T, T, T, F, T, T, T, T, T, F, F, T, T, T, T, T, F, T, T, F, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, F, T, F, T, F, F, F, T, F, T, T, T, T, F, T, T, T, T, T, T, F, F, T, T},
        {T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, F, T, F, T, T, T, T, F, F, T, T, T, F, T, T, T, F, F, T, T, F, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, F},
        {T, T, T, T, F, F, T, T, F, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, F, T, T, F, F, T, T, T, T, T, T, T, T, F, T, F, T},
        {T, T, T, T, T, T, T, T, F, T, T, T, T, T, F, T, T, T, T, T, F, T, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, F, T, T, T, T, F, T, F, T},
        {T, T, T, T, F, F, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, F, T, T},
        {T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, F, T, T, F, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, F, T, T, T, T, F, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, F, F, T, F, T, T, T, T, T, F, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, F, T, T, T, F, F, T, T, T},
        {F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
    };

    private static boolean[][] TABELA02 = {
        {F, T, F, F, F, T, F, F, F, F, T, T, T, F, F, F, T, F, T, T, T, F, T, F, F, F, T, T, F, T, F, F, T, F, T, F, F, T, T, F, F, F, T, T, F, F, T},
        {T, F, F, F, T, F, F, T, F, F, T, T, F, F, F, F, T, F, T, T, T, T, F, T, F, F, F, F, F, T, T, T, T, T, F, F, T, F, F, F, T, F, T, F, T, T, T},
        {T, T, F, T, F, F, T, T, F, T, F, T, F, T, T, T, F, F, T, T, F, F, T, T, T, T, F, F, F, T, F, F, T, T, F, T, F, F, F, F, F, F, T, F, T, T, F},
        {T, T, T, F, F, T, F, T, T, T, F, T, T, F, F, F, T, F, T, F, T, F, T, T, F, F, F, T, F, T, F, F, F, F, F, F, F, T, F, F, T, F, F, T, F, F, T},
        {F, F, F, T, F, T, F, F, F, F, F, T, F, T, F, T, F, T, F, F, T, F, F, T, F, F, T, F, F, F, F, F, T, T, T, F, T, T, T, T, T, F, T, T, F, T, T},
        {F, T, T, T, F, T, F, T, F, F, T, F, F, T, T, F, T, F, T, T, F, T, T, F, T, T, F, F, F, T, F, F, F, T, T, F, F, F, F, T, T, T, T, F, F, T, F},
        {T, T, T, T, F, F, F, T, F, T, F, T, T, F, F, T, F, T, F, F, F, T, F, T, F, T, T, T, T, F, F, F, T, F, F, F, T, F, F, F, F, T, F, T, T, T, T},
        {T, T, T, T, F, F, T, F, T, F, T, F, F, T, F, T, F, T, T, T, T, T, T, F, T, F, T, T, F, T, F, T, F, T, F, T, T, T, T, T, F, F, F, F, F, F, T},
        {F, F, T, F, T, T, F, F, T, F, T, F, T, T, T, T, F, T, T, T, F, F, F, T, F, F, F, T, F, F, F, F, T, F, T, F, F, F, F, T, T, F, F, T, F, T, T},
        {F, T, T, T, F, T, T, T, F, F, T, F, T, T, T, T, T, T, F, F, T, T, F, T, T, F, T, F, F, T, F, F, T, F, F, F, F, T, F, T, F, T, T, T, F, T, F},
        {T, T, F, F, T, F, T, F, T, F, F, T, T, T, T, F, F, F, T, T, T, F, F, T, T, T, T, T, T, F, T, F, T, F, T, F, F, F, F, T, F, T, T, F, T, T, T},
        {F, T, F, T, F, T, T, T, F, T, F, T, T, T, T, T, F, T, F, T, F, T, T, F, F, T, T, T, F, F, F, T, F, F, F, F, T, F, F, F, T, T, T, F, F, T, F},
        {T, T, F, F, F, T, T, F, F, T, T, F, T, F, T, F, F, F, T, F, F, F, T, T, F, T, T, F, F, T, T, F, T, F, T, F, T, T, F, T, F, F, F, F, T, T, F},
        {T, F, T, T, T, F, T, F, F, F, F, F, F, T, F, T, T, T, T, T, F, T, F, T, T, F, T, T, F, F, F, T, F, F, F, F, F, F, T, F, F, T, T, T, F, T, F},
        {F, F, F, T, F, T, F, T, T, F, F, T, F, T, T, F, F, T, T, T, F, F, F, T, T, T, F, F, T, T, T, F, T, F, T, F, F, F, F, F, T, T, T, F, F, T, T},
        {T, F, T, T, T, T, T, T, T, T, F, F, F, F, F, F, F, T, F, T, F, T, F, F, T, T, F, T, F, T, F, T, F, T, T, T, T, F, F, F, F, T, T, T, T, T, F},
        {T, F, T, F, F, T, F, T, F, T, F, T, T, T, F, F, T, F, F, T, T, F, T, F, F, F, F, T, F, F, F, F, F, F, T, T, F, T, F, T, T, T, T, T, T, T, F},
        {T, T, F, T, T, T, T, T, F, T, F, F, T, T, F, T, T, F, F, T, T, T, T, T, T, F, F, F, T, T, T, T, T, T, F, F, T, F, F, F, T, F, F, F, T, F, F},
        {F, F, T, F, F, F, T, T, T, F, F, T, F, F, F, F, T, T, F, T, F, F, T, F, T, F, F, F, T, T, F, F, F, F, T, F, T, F, T, F, F, F, T, T, F, F, F},
        {T, F, F, T, F, F, T, F, F, F, F, F, T, T, F, F, T, T, T, F, F, F, F, F, F, F, F, T, F, T, T, F, F, T, T, F, F, T, T, F, F, F, T, F, T, F, T},
        {T, T, F, T, F, F, F, T, T, T, F, T, T, T, F, T, F, F, F, T, T, F, T, F, F, F, T, T, T, T, F, F, T, T, T, F, T, T, T, F, T, F, T, T, T, T, T},
        {F, T, T, T, F, F, T, T, F, F, F, F, T, F, T, F, F, F, T, F, F, F, T, F, T, F, F, F, F, F, T, T, F, T, T, F, F, F, T, F, T, F, F, T, F, F, T},
        {F, F, T, T, T, T, F, T, F, T, F, T, T, T, F, F, T, F, T, T, T, T, F, T, F, T, T, F, T, F, F, F, T, T, T, T, F, F, F, T, T, T, F, F, T, T, F},
        {T, T, F, F, T, F, T, T, T, T, T, T, F, F, F, F, F, F, F, T, T, F, F, T, F, F, T, T, T, T, F, F, F, T, F, F, T, T, T, F, T, T, T, T, T, F, T},
        {T, T, T, F, T, F, F, T, T, T, F, T, T, T, F, F, F, F, T, T, F, F, T, F, F, F, T, T, T, F, T, T, F, F, T, T, T, F, T, T, T, T, F, F, T, F, F},
        {F, F, F, F, T, F, F, T, F, T, F, T, F, F, T, F, T, T, F, F, T, F, T, F, T, T, T, F, T, F, F, T, T, T, T, T, F, T, F, F, F, T, T, T, F, F, F},
        {F, T, T, T, T, F, F, F, T, T, T, T, F, T, F, T, F, T, F, F, T, F, F, F, T, T, T, T, T, F, F, T, T, T, F, F, T, T, F, F, F, F, T, F, T, F, F},
        {T, F, F, F, F, F, T, F, T, T, T, T, F, F, T, F, F, T, F, T, T, T, F, F, F, F, F, T, T, F, T, T, F, F, F, F, F, F, F, F, T, T, T, F, F, F, F},
        {F, T, T, F, T, F, F, T, F, F, F, T, T, T, F, T, T, T, T, T, T, T, T, F, T, F, F, T, F, T, T, F, F, F, T, T, F, F, F, F, T, F, T, T, T, T, F},
        {F, T, F, T, F, T, T, T, F, T, T, T, T, T, T, T, F, F, F, T, F, T, F, T, T, F, F, F, F, F, T, F, F, F, T, T, F, T, T, F, F, F, F, F, T, T, T},
        {T, F, F, T, T, F, T, T, F, T, F, T, T, F, T, F, T, T, T, T, T, T, F, T, F, T, F, T, F, T, T, F, T, F, F, F, T, T, T, F, F, T, F, F, F, T, T},
        {T, F, T, F, F, F, T, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, T, T, F, T, T, F, F, T, F, T, T, T, T, T, F, T, T, F, F, F, T, T, F, F},
        {F, F, T, T, T, F, F, T, T, F, F, F, T, F, T, F, T, T, F, F, T, F, T, F, F, T, F, F, F, F, F, F, T, F, T, F, T, F, F, F, T, F, T, F, T, F, F},
        {T, T, T, T, F, F, F, T, T, T, F, F, F, F, T, F, F, F, T, T, T, T, T, F, T, T, F, T, T, F, T, T, T, T, F, F, T, T, F, T, F, F, F, F, F, F, T},
        {F, T, T, F, F, T, T, T, T, F, T, T, T, T, T, F, F, T, T, T, F, T, F, F, T, F, F, T, T, F, T, T, F, F, T, F, F, T, T, F, F, T, T, T, F, T, T},
        {F, F, T, F, T, T, T, T, T, F, T, F, T, T, F, T, F, T, T, F, T, T, F, F, T, T, F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, T, T, F, F, F, F},
        {F, F, F, F, T, F, T, F, T, T, T, F, T, F, T, F, T, F, F, T, F, T, T, F, T, F, F, T, F, F, T, F, T, F, F, T, T, F, T, T, F, F, T, T, T, F, T},
        {F, F, F, T, T, F, T, T, F, F, T, F, F, F, F, T, T, T, F, F, T, T, T, T, T, T, T, T, F, F, F, F, T, F, F, F, T, T, F, T, T, T, T, T, F, T, F},
        {T, T, T, T, F, F, T, T, T, F, F, T, F, F, F, F, F, T, T, F, F, T, T, F, F, T, T, F, F, T, F, T, T, F, T, F, F, T, T, T, T, T, T, F, F, F, F},
        {F, F, F, F, F, F, T, T, T, F, T, F, T, T, F, F, T, F, F, F, F, T, T, T, F, F, F, F, F, T, F, T, F, F, F, T, F, F, T, T, F, F, F, T, F, F, T},
        {T, F, T, T, F, F, F, F, T, F, T, F, F, F, F, T, F, T, T, F, T, T, F, T, T, F, T, T, F, T, T, F, T, T, T, T, T, T, T, T, F, F, F, F, T, T, T},
        {T, T, F, T, F, F, F, T, F, T, F, T, T, F, T, T, F, F, F, T, F, T, F, T, T, F, F, T, F, T, F, T, F, F, T, T, T, F, F, F, T, T, T, F, F, T, F},
    };

    private static boolean[][] TABELA03 = {
        {F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, F, T, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F, F, T, F, F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, T},
        {T, F, F, F, F, F, F, F, F, F, F, T, F, T, F, T, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, T, F, F, F, T, F, F, T, F, F, T, F, F, F, F, T, F, F, T, F, F, F, F, T, F, F, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F},
        {F, T, F, T, F, F, F, F, F, T, F, F, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, T, F, T, T, F, T, F, F, F, T, F, T, F, F, F, F, F, F, F},
        {F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, T, T, F, T, F, F, T, F, T, T, F, T, F, F, F, T, F, T, F, F, F, F, F, T, T, F, F, F, F, F, F, F, F, T, F, F, F},
        {F, F, T, F, T, F, F, F, F, F, T, F, F, T, F, F, F, F, T, F, F, F, F, T, F, T, F, F, F, F, T, F, F, F, T, F, F, F, T, F, F, T, T, T, F, F, T, F, F, F, T, T, F, F, F},
        {F, F, F, T, F, F, T, F, T, F, T, F, F, F, F, F, F, F, T, F, T, F, F, F, T, T, T, F, F, T, F, T, F, T, F, F, T, F, F, F, T, T, F, F, F, F, T, F, F, F, F, T, F, F, F},
        {F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, T, T, T, T, F, T, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F, F, F, T, T, F, T, T, T, F, F, F, T, T, F, T},
        {F, F, F, T, T, T, F, T, F, F, F, F, T, T, F, F, T, T, F, F, F, T, T, T, F, F, T, F, F, T, F, F, F, F, F, F, F, T, F, T, F, F, F, T, F, F, F, F, T, F, T, T, F, F, F},
        {F, F, F, T, F, F, F, T, F, T, F, F, F, F, T, T, T, T, T, F, T, T, T, T, T, F, T, F, F, T, F, F, F, F, F, F, F, T, F, T, F, F, F, T, F, T, F, F, F, F, F, F, T, F, F},
        {F, F, F, T, T, F, F, T, F, F, F, F, T, F, T, T, F, F, T, T, F, F, F, F, F, T, T, F, F, T, F, T, F, T, F, T, T, F, F, T, F, F, F, F, F, F, T, F, F, T, F, T, T, F, T},
        {F, F, F, F, F, T, T, T, T, F, F, F, T, F, F, T, F, F, F, F, F, F, F, T, T, F, F, F, T, T, T, T, F, T, F, T, F, F, F, F, F, T, F, T, T, T, T, F, T, F, F, F, T, T, T},
        {F, F, T, T, T, F, T, T, F, T, F, F, F, T, F, F, F, T, F, F, T, F, F, F, F, T, T, T, F, T, F, F, F, F, T, F, T, F, F, F, F, T, T, F, F, F, T, T, T, F, T, T, T, F, T},
        {T, T, T, F, T, F, F, T, F, F, F, T, T, F, T, F, T, F, T, T, T, T, T, T, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, T, F, F, T, T, F, F, F, F, T, T, F, F, T, T, T},
        {F, T, T, T, F, T, T, T, F, F, T, T, T, F, F, F, T, T, F, F, T, T, F, F, F, T, F, T, F, T, F, F, T, F, T, F, F, T, T, F, F, F, F, T, T, T, F, T, T, T, F, F, F, T, F},
        {T, T, T, T, F, F, F, T, F, T, T, F, F, F, F, T, T, F, F, F, T, F, T, F, F, T, T, F, T, T, F, T, T, F, F, F, F, T, T, F, F, T, T, T, T, F, T, T, T, F, T, T, F, F, T},
        {F, T, T, T, T, T, T, T, T, T, T, T, F, T, T, F, T, T, T, T, T, F, F, T, F, T, F, F, F, F, T, F, F, T, T, T, F, F, F, F, T, F, T, T, F, F, F, T, T, F, F, F, T, F, F},
        {T, T, T, F, T, T, T, T, F, T, F, T, F, T, T, F, F, T, F, F, F, T, F, T, F, F, T, T, F, F, F, F, T, F, F, T, T, T, T, T, T, F, T, T, F, T, T, F, T, F, T, F, F, T, T},
        {T, F, F, T, F, F, T, T, T, F, F, F, T, F, T, F, T, T, T, T, F, F, F, T, F, F, T, T, F, T, T, T, T, F, T, T, F, F, T, F, F, F, T, T, T, T, F, T, T, T, F, T, T, T, T},
        {F, F, T, T, T, F, F, T, F, T, T, F, T, T, T, T, T, F, F, F, T, T, T, T, T, T, F, T, T, T, T, F, T, T, T, F, T, T, F, T, F, T, F, F, F, F, F, T, T, F, T, T, F, T, F},
        {T, T, F, T, T, F, T, T, F, F, T, T, F, F, T, T, F, T, F, T, T, T, T, F, T, F, F, F, F, T, T, T, T, F, T, T, T, T, T, T, T, F, T, T, F, F, F, T, T, F, T, T, F, F, T},
        {T, T, T, F, T, T, T, F, T, T, F, T, F, T, T, T, T, T, T, T, F, T, T, T, F, T, T, F, T, T, T, T, T, T, T, F, F, T, F, T, F, T, F, F, F, T, T, F, F, F, T, F, F, F, T},
        {T, T, F, F, T, T, T, T, T, T, F, F, T, F, T, F, T, T, T, T, F, T, T, T, F, F, T, T, T, T, F, T, F, F, F, T, F, T, T, T, T, T, T, T, F, T, T, T, T, F, F, T, T, F, F},
        {T, T, F, F, T, T, T, F, F, T, T, F, T, T, F, F, T, T, F, T, F, F, T, T, T, T, T, T, T, T, T, F, T, T, T, F, T, T, F, T, T, T, F, T, T, T, F, F, F, T, T, T, T, T, F},
        {T, T, F, T, F, T, F, T, T, T, T, F, T, T, F, T, F, T, F, F, T, T, T, T, T, T, T, T, F, F, T, F, F, F, T, F, T, F, T, T, F, T, T, T, T, T, T, T, T, T, F, T, T, T, T},
        {T, T, T, T, F, T, T, T, F, F, F, F, T, F, T, T, T, T, T, F, T, T, T, T, F, T, F, T, T, F, T, T, T, T, T, F, F, T, T, T, F, T, T, T, T, T, F, F, T, F, T, T, T, T, T},
        {T, F, T, T, F, T, T, F, T, T, T, T, T, T, F, T, T, T, F, T, T, T, F, F, T, T, T, T, F, F, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, F, F, T, F, T, T, F, T, F, T},
        {T, T, T, F, T, T, T, F, F, T, T, T, F, T, T, F, F, T, F, T, T, T, T, T, T, T, T, F, T, T, T, T, F, T, F, T, T, T, F, T, T, T, F, T, F, T, T, T, F, T, T, T, T, T, T},
        {F, T, T, T, F, T, F, T, T, T, F, T, T, F, T, T, T, T, T, T, T, F, T, F, F, T, T, F, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, F},
        {T, T, T, F, T, T, T, T, T, T, F, T, F, T, F, F, T, T, T, T, T, T, F, T, T, T, T, T, T, T, F, T, T, T, F, T, T, T, F, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, F, T, T, T, T, F, F, T, T, T, T, T, T, T, F, T, F, T, F, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, F},
        {T, T, T, T, T, T, F, T, F, T, T, T, T, T, T, T, F, T, T, T, F, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, F, T, F},
        {T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, F, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, F, F, T, T},
        {T, T, F, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
    };

    private static boolean[][] TABELA04 = {
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F},
        {F, F, F, T, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, T, F, F, F, F},
        {F, F, F, F, F, T, F, F, F, F, T, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, F, F, F, T, F, F, F, F},
        {F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F, F, F, T, T, F, T, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F},
        {F, T, F, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, T, F, T, F, T, F},
        {F, F, T, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, T, T, F, F, T, F, T, F, F, F, F, F, F, T, F, F, F, T, F, F, F, T, F, F, F, F, F, T, F, F, F, F, F, F},
        {F, T, F, F, F, F, T, F, T, T, F, F, F, F, F, F, F, T, F, F, F, T, T, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, F},
        {F, F, T, T, F, F, T, F, F, F, F, F, F, F, F, T, F, T, F, F, F, F, T, F, F, T, T, F, T, F, T, F, F, F, F, F, F, T, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, T, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, F, T, F, F, F, T, F, F, T, F, F, F, T, T, F, F, F, F, T, F, F, T},
        {T, F, T, F, F, T, F, F, F, F, T, F, F, T, T, F, T, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, T, F, F, F, F, F, F, T, F, F, F, F, F, T, T, F, F, F, F},
        {F, F, F, F, F, F, F, T, F, T, F, T, F, F, F, F, F, F, T, F, F, F, T, F, T, T, T, F, T, F, F, F, F, F, T, T, F, F, T, F, F, F, F, F, T, F, F, F, F, F, F, F, T, T, F, T},
        {F, F, F, T, F, T, T, F, F, T, F, T, F, T, F, F, T, F, F, F, T, T, T, F, F, F, F, F, F, F, F, F, T, F, F, F, T, F, T, F, F, F, F, F, F, F, F, T, T, F, T, F, F, F, T, T},
        {F, T, T, F, F, F, F, T, T, F, F, T, F, F, T, F, T, T, T, F, T, F, F, F, F, F, F, F, T, F, T, T, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, T, F, T, F, F, T, F},
        {F, F, F, F, T, T, T, T, F, F, F, F, F, T, F, F, T, F, T, F, F, F, T, F, T, T, F, F, F, T, T, F, F, T, T, T, F, F, T, F, F, F, F, T, F, F, F, F, F, F, T, T, F, T, T, F},
        {F, F, F, F, F, T, F, T, T, F, T, T, F, T, F, F, F, F, T, F, F, F, F, F, T, T, T, F, T, T, F, F, F, F, T, F, F, T, F, T, F, T, F, F, F, T, F, T, F, T, F, F, F, T, T, T},
        {F, F, F, T, F, T, F, T, T, F, F, F, F, T, T, F, F, F, T, F, F, T, F, F, F, F, F, F, T, T, T, T, T, T, F, F, F, F, T, T, T, F, T, T, F, F, T, F, F, F, F, T, T, F, F, T},
        {F, T, F, F, F, F, F, T, F, F, T, F, T, F, T, T, T, T, F, F, F, T, T, F, T, F, F, F, F, T, T, T, F, F, T, T, T, F, F, T, F, F, T, T, F, F, T, F, F, F, T, F, F, F, T, T},
        {T, F, F, F, F, T, T, F, F, T, F, T, F, F, F, F, F, F, T, T, T, F, F, T, F, T, T, T, F, F, F, T, T, T, F, F, T, F, F, T, F, F, F, T, T, F, T, T, F, F, T, F, T, F, T, T},
        {T, T, F, F, T, T, T, T, T, T, F, F, T, F, F, F, T, T, T, F, F, F, F, T, F, F, T, T, T, F, T, T, T, T, T, T, F, T, F, F, F, F, T, F, F, F, F, T, F, T, F, T, T, F, F, F},
        {T, F, T, T, F, T, T, F, T, T, T, F, F, F, F, T, T, T, F, F, F, T, T, F, T, T, F, F, F, F, T, T, F, T, F, F, F, F, T, F, T, T, T, T, T, F, T, T, T, F, T, F, F, T, F, F},
        {T, T, F, T, T, F, F, T, F, F, T, F, T, T, T, T, F, T, T, F, F, T, T, T, F, T, T, F, F, F, T, T, F, F, T, F, T, F, F, T, F, T, T, F, F, T, T, T, F, T, F, T, F, F, T, F},
        {F, T, T, T, T, T, F, T, T, T, T, F, T, F, T, T, F, F, T, F, T, F, T, T, F, F, T, T, F, T, F, F, F, F, T, F, T, T, F, F, T, T, F, F, T, T, F, T, T, F, T, F, F, T, T, F},
        {T, F, T, T, T, F, F, T, F, T, T, F, T, T, T, F, F, T, F, T, T, F, T, T, F, F, T, F, T, F, T, T, T, T, F, F, F, F, F, F, F, T, T, F, T, T, T, F, T, T, T, T, F, T, T, F},
        {F, T, T, T, T, T, T, T, T, F, F, T, T, F, T, T, F, F, F, T, T, F, T, T, F, T, T, T, T, F, F, T, F, T, T, T, T, F, T, F, F, T, T, T, T, F, T, F, F, F, F, F, T, F, T, T},
        {F, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, F, F, T, F, F, T, T, T, T, T, F, F, T, T, F, F, F, F, T, F, F, T, F, F, T, T, F, T, F, T, T, T, T, T, T, F, T, F, F, T},
        {F, F, F, F, T, T, F, T, T, F, T, F, T, T, T, T, T, T, T, T, T, F, T, F, F, F, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, F, T, F, F, F, T, F, T, T, T, F, T, T, F, F},
        {T, T, F, T, F, T, T, T, F, T, T, F, T, T, F, T, T, F, T, T, T, T, T, F, T, T, T, T, T, F, T, T, T, T, T, F, F, T, F, F, T, T, F, T, F, T, T, T, T, F, T, T, F, T, F, F},
        {T, F, T, T, T, T, F, T, F, F, T, F, F, T, T, T, T, F, T, F, T, T, T, T, T, T, T, F, T, T, T, F, T, T, T, T, T, T, F, T, T, T, T, T, T, F, F, F, T, T, T, T, T, T, F, T},
        {T, T, F, T, T, F, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, F, F, F, T, T, T, F, T, F, T, T, T, T, T, T, F, T, T, T, F, T, F, T, T, T, T, F, F, T, T, F, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, F, T, T, T, T, T, F, T, T, T, T, T, T, F, T, T, F, T, F, T, F, F, T, F, F, F, T, F, F, T, T, T, T, T},
        {F, T, T, T, T, T, T, F, F, T, T, F, T, T, F, T, T, T, T, F, T, F, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, F, F, T, T, T, F, T, T, T, T},
        {T, T, T, T, T, F, T, T, T, T, T, T, T, T, F, T, T, T, T, T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, F, T, F, T, T, T, T, T, T, F, T, F, F, T, T, T},
        {T, T, T, T, T, T, F, T, T, F, T, T, F, T, T, F, T, T, T, T, T, T, T, F, T, T, T, F, T, T, T, F, T, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, F, F, T, T, T, T, F, T, F, T, T},
        {T, T, T, T, T, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, F, T, T, T, T, T, T, F, T},
        {T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, F, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
    };

    private static boolean[][] TABELA05 = {
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
        {F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F},
        {F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F},
        {T, F, F, F, F, F, F, F, F, T, F, F, T, F, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F},
        {F, F, F, F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, T, T, F, F, F},
        {F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, T, T, F, T, T, F, F, F, F, F, T, F, F, F, T, F, F, T, F, F, F, F, T},
        {F, F, F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F, T, F, F, F, F, F, F, T, T, F, F, F, F, F, F, T, T, F, T, T, F, F, F},
        {T, F, F, F, F, F, F, F, F, F, T, F, T, F, F, F, T, T, T, F, F, F, F, T, F, T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F, F, T, F, T},
        {T, F, F, F, T, F, F, F, F, T, F, F, F, F, F, T, F, F, F, T, T, F, F, F, F, F, F, F, F, T, F, F, F, T, T, F, F, F, F, F, F, T, F, T, T, F},
        {F, T, T, F, F, T, F, T, F, F, F, T, F, F, T, F, T, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, F, T, T, F, T, F, T, F, F},
        {T, T, F, F, T, T, F, F, T, F, F, T, F, F, F, F, T, F, T, F, F, F, T, F, F, F, F, F, F, F, F, F, T, T, F, F, F, F, T, F, F, T, T, F, F, F},
        {F, T, F, F, F, F, T, F, F, F, F, F, F, T, F, F, F, F, F, F, T, T, F, T, F, F, T, T, F, T, F, F, F, F, F, F, F, T, F, F, T, F, T, T, T, T},
        {T, F, F, F, T, T, F, F, T, T, F, F, F, F, F, F, F, T, T, T, F, F, F, T, F, F, T, F, T, T, F, F, T, F, F, T, T, F, F, F, F, F, F, F, T, F},
        {F, F, F, F, F, T, F, F, F, F, F, F, F, T, T, T, F, F, T, T, F, T, T, F, F, F, T, F, F, T, F, T, F, F, T, T, F, F, T, F, T, F, F, F, T, T},
        {F, F, F, F, F, T, F, F, F, F, F, F, F, T, T, T, F, F, T, T, F, T, T, F, F, F, T, F, F, T, F, T, F, F, T, T, F, F, T, F, T, F, F, F, T, T},
        {T, F, F, F, F, F, T, F, F, T, F, F, F, F, F, T, F, F, F, F, T, F, T, T, F, T, F, T, T, T, T, T, F, T, T, F, F, T, T, F, F, T, T, F, F, F},
        {T, F, F, T, T, F, F, T, F, T, T, F, T, F, F, F, T, T, T, F, T, F, F, T, T, F, F, F, T, F, T, T, F, F, F, F, F, F, T, F, F, F, F, T, T, T},
        {F, F, F, T, T, F, T, F, T, F, F, F, T, F, F, F, T, F, F, F, F, T, T, T, T, F, T, T, T, T, F, T, F, T, F, T, T, T, F, T, T, F, F, F, F, F},
        {F, F, F, T, F, T, F, F, T, F, T, F, T, F, F, T, F, T, T, T, F, T, F, T, T, F, F, F, T, T, T, T, F, T, F, F, T, F, T, F, T, F, F, F, T, T},
        {F, F, F, F, T, T, T, T, T, T, T, T, F, F, T, T, F, F, T, T, F, T, T, T, F, T, F, F, T, T, F, T, F, F, F, T, F, F, T, T, F, F, T, F, T, F},
        {F, F, T, F, F, F, F, F, T, F, T, T, T, F, T, F, T, T, F, F, F, T, F, F, T, T, T, T, T, T, F, F, T, F, F, T, T, T, F, T, T, T, T, F, T, T},
        {T, T, T, T, T, F, F, F, T, F, T, T, T, F, F, F, F, F, F, T, T, T, T, T, F, F, T, T, T, T, T, T, T, T, F, F, F, T, T, F, T, F, F, F, T, F},
        {F, T, T, T, F, T, T, T, F, F, T, F, F, T, F, T, T, T, T, T, F, F, F, T, T, T, F, F, F, T, T, T, F, T, F, F, T, T, T, F, T, T, T, F, F, T},
        {F, F, T, F, T, F, T, F, T, T, T, F, F, T, T, T, F, F, F, T, F, T, T, F, T, T, T, T, F, T, F, F, T, T, T, T, F, T, T, T, T, F, T, T, T, F},
        {F, T, F, T, F, T, F, T, T, T, F, T, T, T, T, F, T, F, T, T, T, F, T, T, T, F, F, F, T, T, F, T, T, T, F, F, F, T, F, T, T, T, T, T, F, T},
        {T, T, T, T, F, T, T, F, F, F, F, T, T, T, T, T, F, F, F, F, T, T, F, F, T, T, F, T, T, T, F, F, T, T, T, T, T, F, T, T, T, T, T, T, T, F},
        {F, T, F, F, T, T, T, T, T, T, F, T, F, T, F, F, T, T, F, F, T, T, T, F, T, T, T, T, T, F, F, T, T, T, T, T, T, F, F, T, F, T, T, T, T, T},
        {T, T, T, T, F, F, T, T, T, F, T, T, F, T, T, F, F, F, F, T, T, F, T, F, F, T, T, T, T, T, T, T, F, T, T, F, T, T, T, T, T, F, T, T, T, T},
        {T, T, T, T, T, T, F, F, T, T, T, T, T, T, F, T, T, T, T, F, F, T, T, T, F, T, T, T, T, F, T, F, F, F, T, T, T, T, F, F, F, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, F, F, T, T, T, F, T, F, T, T, T, F, T, T, T, T, F, F, T, T, T, T, T, T, T, T, T, F, F, T, T, F, F, F},
        {F, F, F, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, F, T, T, T, T, F, T, T, T, T, T, F, T, T, F, T, T, F, T, F, T},
        {F, F, F, T, T, T, T, T, T, F, T, T, T, T, F, T, F, F, T, T, T, T, T, F, T, T, T, F, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, F, T, T, T, T, T, T, T, F, F, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, F, F, T, T, F, T, T, F, T, T, T, T},
        {F, T, T, T, T, T, T, T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, F, T, F},
        {T, F, T, T, T, T, F, T, T, T, F, T, T, F, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, F, T, T},
        {T, T, T, F, T, F, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, F, T, F, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T},
        {T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, F, T, T, T, T, F},
        {T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
        {T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
    };

    public static void main(String[] args) {
        System.out.println(Prva.vednoBoljRes(TABELA01));
        System.out.println(Prva.vednoBoljRes(TABELA02));
        System.out.println(Prva.vednoBoljRes(TABELA03));
        System.out.println(Prva.vednoBoljRes(TABELA04));
        System.out.println(Prva.vednoBoljRes(TABELA05));
    }
}
