
import java.util.Arrays;

public class Test43 {

    public static void main(String[] args) {
        Druga.Oseba oseba1 = new Druga.Oseba("Breda Bevc");
        Druga.Oseba[] osebaa1 = {oseba1};
        Druga.Clanek[] clanki1 = {
            new Druga.Clanek("A", osebaa1, 24),
            new Druga.Clanek("A", osebaa1, 32),
            new Druga.Clanek("A", osebaa1, 55),
            new Druga.Clanek("A", osebaa1, 20),
            new Druga.Clanek("A", osebaa1, 88),
            new Druga.Clanek("A", osebaa1, 2),
            new Druga.Clanek("A", osebaa1, 58),
            new Druga.Clanek("A", osebaa1, 34),
            new Druga.Clanek("A", osebaa1, 83),
            new Druga.Clanek("A", osebaa1, 10),
            new Druga.Clanek("A", osebaa1, 17),
            new Druga.Clanek("A", osebaa1, 83),
            new Druga.Clanek("A", osebaa1, 15),
            new Druga.Clanek("A", osebaa1, 79),
            new Druga.Clanek("A", osebaa1, 43),
            new Druga.Clanek("A", osebaa1, 93),
            new Druga.Clanek("A", osebaa1, 68),
            new Druga.Clanek("A", osebaa1, 100),
            new Druga.Clanek("A", osebaa1, 15),
            new Druga.Clanek("A", osebaa1, 16),
            new Druga.Clanek("A", osebaa1, 85),
            new Druga.Clanek("A", osebaa1, 11),
            new Druga.Clanek("A", osebaa1, 0),
            new Druga.Clanek("A", osebaa1, 96),
            new Druga.Clanek("A", osebaa1, 5),
            new Druga.Clanek("A", osebaa1, 13),
            new Druga.Clanek("A", osebaa1, 71),
            new Druga.Clanek("A", osebaa1, 77),
            new Druga.Clanek("A", osebaa1, 25),
            new Druga.Clanek("A", osebaa1, 40),
            new Druga.Clanek("A", osebaa1, 47),
            new Druga.Clanek("A", osebaa1, 38),
            new Druga.Clanek("A", osebaa1, 54),
            new Druga.Clanek("A", osebaa1, 99),
            new Druga.Clanek("A", osebaa1, 30),
            new Druga.Clanek("A", osebaa1, 92),
            new Druga.Clanek("A", osebaa1, 81),
            new Druga.Clanek("A", osebaa1, 90),
            new Druga.Clanek("A", osebaa1, 17),
            new Druga.Clanek("A", osebaa1, 81),
            new Druga.Clanek("A", osebaa1, 85),
            new Druga.Clanek("A", osebaa1, 76),
        };
        oseba1.nastaviClanke(clanki1);
        System.out.println(oseba1.hIndeks());

        Druga.Oseba oseba2 = new Druga.Oseba("Leopold Mihevc");
        Druga.Oseba[] osebaa2 = {oseba2};
        Druga.Clanek[] clanki2 = {
            new Druga.Clanek("A", osebaa2, 63),
            new Druga.Clanek("A", osebaa2, 92),
            new Druga.Clanek("A", osebaa2, 21),
            new Druga.Clanek("A", osebaa2, 78),
            new Druga.Clanek("A", osebaa2, 60),
            new Druga.Clanek("A", osebaa2, 95),
            new Druga.Clanek("A", osebaa2, 27),
            new Druga.Clanek("A", osebaa2, 58),
            new Druga.Clanek("A", osebaa2, 97),
            new Druga.Clanek("A", osebaa2, 30),
            new Druga.Clanek("A", osebaa2, 54),
            new Druga.Clanek("A", osebaa2, 53),
            new Druga.Clanek("A", osebaa2, 73),
            new Druga.Clanek("A", osebaa2, 70),
            new Druga.Clanek("A", osebaa2, 53),
            new Druga.Clanek("A", osebaa2, 5),
            new Druga.Clanek("A", osebaa2, 75),
            new Druga.Clanek("A", osebaa2, 13),
            new Druga.Clanek("A", osebaa2, 70),
            new Druga.Clanek("A", osebaa2, 75),
            new Druga.Clanek("A", osebaa2, 69),
            new Druga.Clanek("A", osebaa2, 23),
            new Druga.Clanek("A", osebaa2, 58),
            new Druga.Clanek("A", osebaa2, 41),
            new Druga.Clanek("A", osebaa2, 82),
            new Druga.Clanek("A", osebaa2, 35),
            new Druga.Clanek("A", osebaa2, 40),
            new Druga.Clanek("A", osebaa2, 18),
            new Druga.Clanek("A", osebaa2, 16),
            new Druga.Clanek("A", osebaa2, 60),
            new Druga.Clanek("A", osebaa2, 96),
            new Druga.Clanek("A", osebaa2, 73),
            new Druga.Clanek("A", osebaa2, 19),
            new Druga.Clanek("A", osebaa2, 93),
            new Druga.Clanek("A", osebaa2, 52),
            new Druga.Clanek("A", osebaa2, 67),
            new Druga.Clanek("A", osebaa2, 20),
            new Druga.Clanek("A", osebaa2, 70),
            new Druga.Clanek("A", osebaa2, 86),
            new Druga.Clanek("A", osebaa2, 94),
            new Druga.Clanek("A", osebaa2, 1),
            new Druga.Clanek("A", osebaa2, 85),
        };
        oseba2.nastaviClanke(clanki2);
        System.out.println(oseba2.hIndeks());

        Druga.Oseba oseba3 = new Druga.Oseba("Sandi Vehar");
        Druga.Oseba[] osebaa3 = {oseba3};
        Druga.Clanek[] clanki3 = {
            new Druga.Clanek("A", osebaa3, 89),
            new Druga.Clanek("A", osebaa3, 92),
            new Druga.Clanek("A", osebaa3, 6),
            new Druga.Clanek("A", osebaa3, 81),
            new Druga.Clanek("A", osebaa3, 21),
            new Druga.Clanek("A", osebaa3, 6),
            new Druga.Clanek("A", osebaa3, 70),
            new Druga.Clanek("A", osebaa3, 63),
            new Druga.Clanek("A", osebaa3, 92),
            new Druga.Clanek("A", osebaa3, 80),
            new Druga.Clanek("A", osebaa3, 27),
            new Druga.Clanek("A", osebaa3, 39),
            new Druga.Clanek("A", osebaa3, 76),
            new Druga.Clanek("A", osebaa3, 41),
            new Druga.Clanek("A", osebaa3, 72),
            new Druga.Clanek("A", osebaa3, 44),
            new Druga.Clanek("A", osebaa3, 9),
            new Druga.Clanek("A", osebaa3, 50),
            new Druga.Clanek("A", osebaa3, 23),
            new Druga.Clanek("A", osebaa3, 90),
            new Druga.Clanek("A", osebaa3, 94),
            new Druga.Clanek("A", osebaa3, 7),
            new Druga.Clanek("A", osebaa3, 1),
            new Druga.Clanek("A", osebaa3, 75),
            new Druga.Clanek("A", osebaa3, 32),
            new Druga.Clanek("A", osebaa3, 33),
            new Druga.Clanek("A", osebaa3, 69),
            new Druga.Clanek("A", osebaa3, 100),
            new Druga.Clanek("A", osebaa3, 78),
            new Druga.Clanek("A", osebaa3, 22),
            new Druga.Clanek("A", osebaa3, 82),
            new Druga.Clanek("A", osebaa3, 54),
            new Druga.Clanek("A", osebaa3, 3),
            new Druga.Clanek("A", osebaa3, 59),
            new Druga.Clanek("A", osebaa3, 52),
            new Druga.Clanek("A", osebaa3, 12),
            new Druga.Clanek("A", osebaa3, 47),
            new Druga.Clanek("A", osebaa3, 81),
            new Druga.Clanek("A", osebaa3, 95),
            new Druga.Clanek("A", osebaa3, 63),
            new Druga.Clanek("A", osebaa3, 9),
            new Druga.Clanek("A", osebaa3, 77),
        };
        oseba3.nastaviClanke(clanki3);
        System.out.println(oseba3.hIndeks());

    }
}
