
import java.util.Arrays;

public class Test44 {

    public static void main(String[] args) {
        Druga.Oseba oseba1 = new Druga.Oseba("Tatjana Tavzes");
        Druga.Oseba[] osebaa1 = {oseba1};
        Druga.Clanek[] clanki1 = {
            new Druga.Clanek("A", osebaa1, 243),
            new Druga.Clanek("A", osebaa1, 109),
            new Druga.Clanek("A", osebaa1, 260),
            new Druga.Clanek("A", osebaa1, 398),
            new Druga.Clanek("A", osebaa1, 71),
            new Druga.Clanek("A", osebaa1, 324),
            new Druga.Clanek("A", osebaa1, 367),
            new Druga.Clanek("A", osebaa1, 129),
            new Druga.Clanek("A", osebaa1, 137),
            new Druga.Clanek("A", osebaa1, 168),
            new Druga.Clanek("A", osebaa1, 450),
            new Druga.Clanek("A", osebaa1, 227),
            new Druga.Clanek("A", osebaa1, 177),
            new Druga.Clanek("A", osebaa1, 67),
            new Druga.Clanek("A", osebaa1, 349),
            new Druga.Clanek("A", osebaa1, 400),
            new Druga.Clanek("A", osebaa1, 471),
            new Druga.Clanek("A", osebaa1, 162),
            new Druga.Clanek("A", osebaa1, 11),
            new Druga.Clanek("A", osebaa1, 472),
            new Druga.Clanek("A", osebaa1, 312),
            new Druga.Clanek("A", osebaa1, 342),
            new Druga.Clanek("A", osebaa1, 387),
            new Druga.Clanek("A", osebaa1, 185),
            new Druga.Clanek("A", osebaa1, 69),
            new Druga.Clanek("A", osebaa1, 321),
            new Druga.Clanek("A", osebaa1, 251),
            new Druga.Clanek("A", osebaa1, 137),
            new Druga.Clanek("A", osebaa1, 495),
            new Druga.Clanek("A", osebaa1, 325),
            new Druga.Clanek("A", osebaa1, 351),
            new Druga.Clanek("A", osebaa1, 52),
            new Druga.Clanek("A", osebaa1, 217),
            new Druga.Clanek("A", osebaa1, 176),
            new Druga.Clanek("A", osebaa1, 55),
            new Druga.Clanek("A", osebaa1, 314),
            new Druga.Clanek("A", osebaa1, 341),
            new Druga.Clanek("A", osebaa1, 62),
            new Druga.Clanek("A", osebaa1, 108),
            new Druga.Clanek("A", osebaa1, 461),
            new Druga.Clanek("A", osebaa1, 186),
            new Druga.Clanek("A", osebaa1, 253),
            new Druga.Clanek("A", osebaa1, 385),
            new Druga.Clanek("A", osebaa1, 340),
            new Druga.Clanek("A", osebaa1, 239),
            new Druga.Clanek("A", osebaa1, 212),
            new Druga.Clanek("A", osebaa1, 431),
            new Druga.Clanek("A", osebaa1, 4),
            new Druga.Clanek("A", osebaa1, 380),
            new Druga.Clanek("A", osebaa1, 376),
        };
        oseba1.nastaviClanke(clanki1);
        System.out.println(oseba1.hIndeks());

        Druga.Oseba oseba2 = new Druga.Oseba("Otilija Kobal");
        Druga.Oseba[] osebaa2 = {oseba2};
        Druga.Clanek[] clanki2 = {
            new Druga.Clanek("A", osebaa2, 236),
            new Druga.Clanek("A", osebaa2, 360),
            new Druga.Clanek("A", osebaa2, 436),
            new Druga.Clanek("A", osebaa2, 231),
            new Druga.Clanek("A", osebaa2, 345),
            new Druga.Clanek("A", osebaa2, 408),
            new Druga.Clanek("A", osebaa2, 228),
            new Druga.Clanek("A", osebaa2, 305),
            new Druga.Clanek("A", osebaa2, 130),
            new Druga.Clanek("A", osebaa2, 173),
            new Druga.Clanek("A", osebaa2, 260),
            new Druga.Clanek("A", osebaa2, 354),
            new Druga.Clanek("A", osebaa2, 357),
            new Druga.Clanek("A", osebaa2, 371),
            new Druga.Clanek("A", osebaa2, 367),
            new Druga.Clanek("A", osebaa2, 234),
            new Druga.Clanek("A", osebaa2, 37),
            new Druga.Clanek("A", osebaa2, 449),
            new Druga.Clanek("A", osebaa2, 489),
            new Druga.Clanek("A", osebaa2, 241),
            new Druga.Clanek("A", osebaa2, 268),
            new Druga.Clanek("A", osebaa2, 317),
            new Druga.Clanek("A", osebaa2, 409),
            new Druga.Clanek("A", osebaa2, 172),
            new Druga.Clanek("A", osebaa2, 317),
            new Druga.Clanek("A", osebaa2, 168),
            new Druga.Clanek("A", osebaa2, 69),
            new Druga.Clanek("A", osebaa2, 121),
            new Druga.Clanek("A", osebaa2, 288),
            new Druga.Clanek("A", osebaa2, 50),
            new Druga.Clanek("A", osebaa2, 3),
            new Druga.Clanek("A", osebaa2, 407),
            new Druga.Clanek("A", osebaa2, 108),
            new Druga.Clanek("A", osebaa2, 171),
            new Druga.Clanek("A", osebaa2, 414),
            new Druga.Clanek("A", osebaa2, 182),
            new Druga.Clanek("A", osebaa2, 493),
            new Druga.Clanek("A", osebaa2, 23),
            new Druga.Clanek("A", osebaa2, 93),
            new Druga.Clanek("A", osebaa2, 109),
            new Druga.Clanek("A", osebaa2, 436),
            new Druga.Clanek("A", osebaa2, 261),
            new Druga.Clanek("A", osebaa2, 128),
            new Druga.Clanek("A", osebaa2, 500),
            new Druga.Clanek("A", osebaa2, 415),
            new Druga.Clanek("A", osebaa2, 222),
            new Druga.Clanek("A", osebaa2, 327),
            new Druga.Clanek("A", osebaa2, 204),
            new Druga.Clanek("A", osebaa2, 167),
            new Druga.Clanek("A", osebaa2, 243),
        };
        oseba2.nastaviClanke(clanki2);
        System.out.println(oseba2.hIndeks());

        Druga.Oseba oseba3 = new Druga.Oseba("Jana Andrejc");
        Druga.Oseba[] osebaa3 = {oseba3};
        Druga.Clanek[] clanki3 = {
            new Druga.Clanek("A", osebaa3, 321),
            new Druga.Clanek("A", osebaa3, 119),
            new Druga.Clanek("A", osebaa3, 400),
            new Druga.Clanek("A", osebaa3, 408),
            new Druga.Clanek("A", osebaa3, 468),
            new Druga.Clanek("A", osebaa3, 118),
            new Druga.Clanek("A", osebaa3, 349),
            new Druga.Clanek("A", osebaa3, 420),
            new Druga.Clanek("A", osebaa3, 99),
            new Druga.Clanek("A", osebaa3, 456),
            new Druga.Clanek("A", osebaa3, 499),
            new Druga.Clanek("A", osebaa3, 143),
            new Druga.Clanek("A", osebaa3, 28),
            new Druga.Clanek("A", osebaa3, 369),
            new Druga.Clanek("A", osebaa3, 447),
            new Druga.Clanek("A", osebaa3, 1),
            new Druga.Clanek("A", osebaa3, 75),
            new Druga.Clanek("A", osebaa3, 236),
            new Druga.Clanek("A", osebaa3, 252),
            new Druga.Clanek("A", osebaa3, 288),
            new Druga.Clanek("A", osebaa3, 197),
            new Druga.Clanek("A", osebaa3, 17),
            new Druga.Clanek("A", osebaa3, 21),
            new Druga.Clanek("A", osebaa3, 321),
            new Druga.Clanek("A", osebaa3, 307),
            new Druga.Clanek("A", osebaa3, 335),
            new Druga.Clanek("A", osebaa3, 201),
            new Druga.Clanek("A", osebaa3, 381),
            new Druga.Clanek("A", osebaa3, 86),
            new Druga.Clanek("A", osebaa3, 283),
            new Druga.Clanek("A", osebaa3, 468),
            new Druga.Clanek("A", osebaa3, 387),
            new Druga.Clanek("A", osebaa3, 153),
            new Druga.Clanek("A", osebaa3, 197),
            new Druga.Clanek("A", osebaa3, 487),
            new Druga.Clanek("A", osebaa3, 203),
            new Druga.Clanek("A", osebaa3, 105),
            new Druga.Clanek("A", osebaa3, 34),
            new Druga.Clanek("A", osebaa3, 97),
            new Druga.Clanek("A", osebaa3, 191),
            new Druga.Clanek("A", osebaa3, 275),
            new Druga.Clanek("A", osebaa3, 315),
            new Druga.Clanek("A", osebaa3, 65),
            new Druga.Clanek("A", osebaa3, 320),
            new Druga.Clanek("A", osebaa3, 172),
            new Druga.Clanek("A", osebaa3, 479),
            new Druga.Clanek("A", osebaa3, 324),
            new Druga.Clanek("A", osebaa3, 96),
            new Druga.Clanek("A", osebaa3, 4),
            new Druga.Clanek("A", osebaa3, 219),
        };
        oseba3.nastaviClanke(clanki3);
        System.out.println(oseba3.hIndeks());

    }
}
