// _NE_ODSTRANI_

import java.awt.*;

public class Test42 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaNavpicno(4, 4, 1),
            new Tretja.LadjaVodoravno(13, 3, 14),
            new Tretja.LadjaNavpicno(0, 15, 6),
            new Tretja.LadjaVodoravno(2, 12, 2),
            new Tretja.LadjaNavpicno(3, 2, 7),
            new Tretja.LadjaNavpicno(2, 7, 8),
            new Tretja.LadjaVodoravno(15, 0, 17),
            new Tretja.LadjaNavpicno(5, 11, 6),
            new Tretja.LadjaVodoravno(0, 2, 11),
            new Tretja.LadjaVodoravno(11, 0, 10),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(7, 11),
            new Tretja.Strel(5, 12),
            new Tretja.Strel(0, 10),
            new Tretja.Strel(8, 16),
            new Tretja.Strel(0, 11),
            new Tretja.Strel(7, 0),
            new Tretja.Strel(3, 15),
            new Tretja.Strel(6, 15),
            new Tretja.Strel(15, 9),
            new Tretja.Strel(10, 6),
            new Tretja.Strel(11, 3),
            new Tretja.Strel(13, 4),
            new Tretja.Strel(6, 10),
            new Tretja.Strel(3, 8),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(11, 11),
            new Tretja.Strel(15, 10),
            new Tretja.Strel(6, 8),
            new Tretja.Strel(12, 16),
            new Tretja.Strel(1, 9),
            new Tretja.Strel(0, 13),
            new Tretja.Strel(4, 4),
            new Tretja.Strel(14, 11),
            new Tretja.Strel(1, 2),
            new Tretja.Strel(3, 7),
            new Tretja.Strel(13, 8),
            new Tretja.Strel(0, 2),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(11, 14),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(13, 12),
            new Tretja.Strel(15, 16),
            new Tretja.Strel(2, 1),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(1, 10),
            new Tretja.Strel(0, 3),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(4, 7),
            new Tretja.Strel(12, 4),
            new Tretja.Strel(8, 13),
            new Tretja.Strel(15, 0),
            new Tretja.Strel(6, 5),
            new Tretja.Strel(9, 8),
            new Tretja.Strel(1, 16),
            new Tretja.Strel(10, 7),
            new Tretja.Strel(14, 7),
            new Tretja.Strel(9, 0),
            new Tretja.Strel(5, 3),
            new Tretja.Strel(15, 2),
            new Tretja.Strel(16, 3),
            new Tretja.Strel(8, 4),
            new Tretja.Strel(12, 11),
            new Tretja.Strel(10, 15),
            new Tretja.Strel(9, 1),
            new Tretja.Strel(13, 3),
            new Tretja.Strel(10, 5),
            new Tretja.Strel(9, 5),
            new Tretja.Strel(7, 14),
            new Tretja.Strel(16, 1),
            new Tretja.Strel(10, 3),
            new Tretja.Strel(8, 6),
            new Tretja.Strel(12, 5),
            new Tretja.Strel(16, 11),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(0, 8),
            new Tretja.Strel(9, 16),
            new Tretja.Strel(4, 15),
            new Tretja.Strel(0, 15),
            new Tretja.Strel(16, 10),
            new Tretja.Strel(1, 12),
            new Tretja.Strel(11, 16),
            new Tretja.Strel(0, 6),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(6, 0),
            new Tretja.Strel(15, 11),
        };

        Tretja tretja = new Tretja(17, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat42.png", "544x612"}, "Potapljanje ladjic");
    }
}
