// _NE_ODSTRANI_

import java.awt.*;

public class Test26 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {};
        Tretja.Strel[] streli = {
            new Tretja.Strel(12, 2),
            new Tretja.Strel(7, 8),
            new Tretja.Strel(7, 13),
            new Tretja.Strel(7, 0),
            new Tretja.Strel(7, 10),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(9, 11),
            new Tretja.Strel(0, 13),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(11, 3),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(12, 6),
            new Tretja.Strel(10, 10),
            new Tretja.Strel(6, 11),
            new Tretja.Strel(0, 2),
            new Tretja.Strel(9, 5),
            new Tretja.Strel(11, 10),
            new Tretja.Strel(9, 12),
            new Tretja.Strel(10, 0),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(13, 13),
            new Tretja.Strel(7, 12),
            new Tretja.Strel(1, 10),
            new Tretja.Strel(4, 4),
            new Tretja.Strel(1, 4),
            new Tretja.Strel(5, 11),
            new Tretja.Strel(4, 2),
            new Tretja.Strel(7, 1),
            new Tretja.Strel(10, 4),
            new Tretja.Strel(12, 13),
            new Tretja.Strel(3, 4),
            new Tretja.Strel(0, 0),
            new Tretja.Strel(13, 8),
            new Tretja.Strel(2, 3),
            new Tretja.Strel(10, 5),
            new Tretja.Strel(8, 8),
            new Tretja.Strel(11, 0),
            new Tretja.Strel(3, 8),
            new Tretja.Strel(1, 11),
            new Tretja.Strel(0, 6),
            new Tretja.Strel(3, 7),
            new Tretja.Strel(13, 1),
            new Tretja.Strel(12, 10),
            new Tretja.Strel(2, 5),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(9, 1),
            new Tretja.Strel(1, 8),
            new Tretja.Strel(4, 7),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(6, 9),
            new Tretja.Strel(10, 3),
            new Tretja.Strel(13, 3),
            new Tretja.Strel(12, 1),
            new Tretja.Strel(8, 1),
            new Tretja.Strel(2, 7),
            new Tretja.Strel(13, 11),
            new Tretja.Strel(7, 5),
            new Tretja.Strel(10, 13),
            new Tretja.Strel(6, 1),
            new Tretja.Strel(1, 9),
            new Tretja.Strel(8, 13),
            new Tretja.Strel(10, 7),
            new Tretja.Strel(5, 8),
            new Tretja.Strel(11, 8),
            new Tretja.Strel(8, 11),
            new Tretja.Strel(5, 0),
            new Tretja.Strel(8, 10),
            new Tretja.Strel(4, 6),
            new Tretja.Strel(12, 9),
            new Tretja.Strel(10, 1),
            new Tretja.Strel(8, 3),
            new Tretja.Strel(7, 9),
            new Tretja.Strel(0, 7),
            new Tretja.Strel(8, 12),
            new Tretja.Strel(10, 12),
            new Tretja.Strel(0, 8),
            new Tretja.Strel(13, 7),
            new Tretja.Strel(1, 12),
            new Tretja.Strel(5, 6),
            new Tretja.Strel(13, 9),
            new Tretja.Strel(5, 12),
            new Tretja.Strel(6, 12),
            new Tretja.Strel(11, 9),
            new Tretja.Strel(8, 7),
            new Tretja.Strel(0, 1),
            new Tretja.Strel(7, 3),
            new Tretja.Strel(4, 10),
            new Tretja.Strel(5, 2),
            new Tretja.Strel(1, 2),
            new Tretja.Strel(13, 4),
            new Tretja.Strel(2, 1),
            new Tretja.Strel(2, 8),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(11, 7),
            new Tretja.Strel(13, 0),
            new Tretja.Strel(3, 9),
            new Tretja.Strel(4, 9),
            new Tretja.Strel(6, 2),
        };

        Tretja tretja = new Tretja(14, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat26.png", "588x504"}, "Potapljanje ladjic");
    }
}
