// _NE_ODSTRANI_

import java.awt.*;

public class Test46 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaNavpicno(14, 3, 1),
            new Tretja.LadjaVodoravno(11, 7, 6),
            new Tretja.LadjaVodoravno(3, 4, 2),
            new Tretja.LadjaNavpicno(7, 6, 1),
            new Tretja.LadjaVodoravno(1, 5, 6),
            new Tretja.LadjaNavpicno(1, 0, 11),
            new Tretja.LadjaVodoravno(9, 8, 2),
            new Tretja.LadjaNavpicno(0, 14, 15),
            new Tretja.LadjaNavpicno(0, 2, 11),
            new Tretja.LadjaNavpicno(4, 9, 2),
            new Tretja.LadjaVodoravno(6, 11, 2),
            new Tretja.LadjaVodoravno(14, 8, 4),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(7, 14),
            new Tretja.Strel(13, 13),
            new Tretja.Strel(6, 8),
            new Tretja.Strel(13, 2),
            new Tretja.Strel(8, 11),
            new Tretja.Strel(7, 1),
            new Tretja.Strel(10, 9),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(9, 0),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(12, 8),
            new Tretja.Strel(2, 14),
            new Tretja.Strel(10, 5),
            new Tretja.Strel(6, 0),
            new Tretja.Strel(13, 10),
            new Tretja.Strel(12, 10),
            new Tretja.Strel(2, 10),
            new Tretja.Strel(1, 10),
            new Tretja.Strel(5, 6),
            new Tretja.Strel(7, 11),
            new Tretja.Strel(3, 10),
            new Tretja.Strel(8, 2),
            new Tretja.Strel(13, 0),
            new Tretja.Strel(10, 13),
            new Tretja.Strel(10, 2),
            new Tretja.Strel(4, 9),
            new Tretja.Strel(5, 13),
            new Tretja.Strel(13, 9),
            new Tretja.Strel(3, 7),
            new Tretja.Strel(13, 8),
            new Tretja.Strel(7, 2),
            new Tretja.Strel(9, 1),
            new Tretja.Strel(13, 3),
            new Tretja.Strel(8, 7),
            new Tretja.Strel(14, 3),
            new Tretja.Strel(2, 13),
            new Tretja.Strel(4, 13),
            new Tretja.Strel(14, 8),
            new Tretja.Strel(0, 14),
            new Tretja.Strel(12, 6),
            new Tretja.Strel(8, 10),
            new Tretja.Strel(1, 1),
            new Tretja.Strel(11, 12),
            new Tretja.Strel(2, 3),
            new Tretja.Strel(12, 1),
            new Tretja.Strel(4, 6),
            new Tretja.Strel(9, 10),
            new Tretja.Strel(11, 11),
            new Tretja.Strel(1, 6),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(10, 6),
            new Tretja.Strel(0, 13),
            new Tretja.Strel(7, 7),
            new Tretja.Strel(12, 5),
            new Tretja.Strel(4, 3),
            new Tretja.Strel(9, 6),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(2, 9),
            new Tretja.Strel(6, 5),
            new Tretja.Strel(2, 8),
            new Tretja.Strel(14, 14),
            new Tretja.Strel(4, 2),
            new Tretja.Strel(0, 1),
            new Tretja.Strel(0, 9),
            new Tretja.Strel(11, 7),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(8, 14),
            new Tretja.Strel(0, 3),
            new Tretja.Strel(9, 2),
            new Tretja.Strel(9, 13),
            new Tretja.Strel(13, 6),
            new Tretja.Strel(5, 9),
            new Tretja.Strel(7, 13),
            new Tretja.Strel(2, 2),
            new Tretja.Strel(5, 11),
            new Tretja.Strel(14, 6),
            new Tretja.Strel(14, 10),
            new Tretja.Strel(9, 8),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(1, 3),
            new Tretja.Strel(13, 14),
            new Tretja.Strel(8, 5),
            new Tretja.Strel(11, 0),
            new Tretja.Strel(8, 4),
            new Tretja.Strel(6, 2),
            new Tretja.Strel(1, 7),
            new Tretja.Strel(7, 8),
        };

        Tretja tretja = new Tretja(15, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat46.png", "480x720"}, "Potapljanje ladjic");
    }
}
