// _NE_ODSTRANI_

import java.awt.*;

public class Test27 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {};
        Tretja.Strel[] streli = {
            new Tretja.Strel(2, 9),
            new Tretja.Strel(16, 1),
            new Tretja.Strel(0, 13),
            new Tretja.Strel(13, 6),
            new Tretja.Strel(16, 5),
            new Tretja.Strel(8, 7),
            new Tretja.Strel(1, 12),
            new Tretja.Strel(0, 15),
            new Tretja.Strel(3, 16),
            new Tretja.Strel(17, 0),
            new Tretja.Strel(8, 6),
            new Tretja.Strel(16, 10),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(14, 17),
            new Tretja.Strel(6, 2),
            new Tretja.Strel(9, 15),
            new Tretja.Strel(18, 17),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(9, 2),
            new Tretja.Strel(2, 14),
            new Tretja.Strel(18, 15),
            new Tretja.Strel(2, 8),
            new Tretja.Strel(7, 10),
            new Tretja.Strel(1, 1),
            new Tretja.Strel(14, 2),
            new Tretja.Strel(3, 5),
            new Tretja.Strel(16, 7),
            new Tretja.Strel(18, 10),
            new Tretja.Strel(9, 12),
            new Tretja.Strel(16, 12),
            new Tretja.Strel(6, 5),
            new Tretja.Strel(16, 13),
            new Tretja.Strel(6, 1),
            new Tretja.Strel(5, 18),
            new Tretja.Strel(5, 5),
            new Tretja.Strel(3, 9),
            new Tretja.Strel(15, 1),
            new Tretja.Strel(14, 7),
            new Tretja.Strel(1, 18),
            new Tretja.Strel(6, 8),
            new Tretja.Strel(7, 14),
            new Tretja.Strel(9, 4),
            new Tretja.Strel(9, 1),
            new Tretja.Strel(10, 3),
            new Tretja.Strel(8, 1),
            new Tretja.Strel(9, 14),
            new Tretja.Strel(15, 7),
            new Tretja.Strel(1, 16),
            new Tretja.Strel(1, 2),
            new Tretja.Strel(12, 1),
            new Tretja.Strel(13, 2),
            new Tretja.Strel(14, 4),
            new Tretja.Strel(11, 12),
            new Tretja.Strel(10, 7),
            new Tretja.Strel(14, 12),
            new Tretja.Strel(3, 10),
            new Tretja.Strel(7, 7),
            new Tretja.Strel(11, 4),
            new Tretja.Strel(9, 11),
            new Tretja.Strel(1, 5),
            new Tretja.Strel(5, 4),
            new Tretja.Strel(17, 11),
            new Tretja.Strel(18, 12),
            new Tretja.Strel(10, 13),
            new Tretja.Strel(0, 18),
            new Tretja.Strel(1, 3),
            new Tretja.Strel(10, 1),
            new Tretja.Strel(18, 18),
            new Tretja.Strel(0, 17),
            new Tretja.Strel(18, 7),
            new Tretja.Strel(13, 12),
            new Tretja.Strel(15, 0),
            new Tretja.Strel(11, 16),
            new Tretja.Strel(14, 0),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(5, 13),
            new Tretja.Strel(0, 4),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(5, 8),
            new Tretja.Strel(10, 5),
            new Tretja.Strel(16, 15),
            new Tretja.Strel(16, 18),
            new Tretja.Strel(12, 4),
            new Tretja.Strel(13, 5),
            new Tretja.Strel(17, 10),
            new Tretja.Strel(5, 12),
            new Tretja.Strel(1, 4),
            new Tretja.Strel(3, 4),
            new Tretja.Strel(5, 3),
            new Tretja.Strel(15, 8),
            new Tretja.Strel(7, 4),
            new Tretja.Strel(5, 9),
            new Tretja.Strel(9, 7),
            new Tretja.Strel(11, 7),
            new Tretja.Strel(10, 12),
            new Tretja.Strel(4, 10),
            new Tretja.Strel(13, 18),
            new Tretja.Strel(5, 11),
            new Tretja.Strel(2, 4),
            new Tretja.Strel(4, 7),
            new Tretja.Strel(13, 15),
            new Tretja.Strel(6, 18),
            new Tretja.Strel(8, 15),
            new Tretja.Strel(1, 13),
            new Tretja.Strel(12, 0),
            new Tretja.Strel(18, 9),
            new Tretja.Strel(17, 18),
            new Tretja.Strel(11, 14),
            new Tretja.Strel(10, 6),
            new Tretja.Strel(1, 8),
            new Tretja.Strel(14, 14),
            new Tretja.Strel(8, 13),
            new Tretja.Strel(2, 15),
            new Tretja.Strel(14, 16),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(8, 8),
            new Tretja.Strel(16, 4),
            new Tretja.Strel(7, 5),
            new Tretja.Strel(14, 9),
        };

        Tretja tretja = new Tretja(19, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat27.png", "798x456"}, "Potapljanje ladjic");
    }
}
