// _NE_ODSTRANI_

import java.awt.*;

public class Test48 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaNavpicno(7, 1, 4),
            new Tretja.LadjaNavpicno(0, 10, 16),
            new Tretja.LadjaNavpicno(13, 5, 1),
            new Tretja.LadjaNavpicno(2, 14, 13),
            new Tretja.LadjaVodoravno(3, 0, 9),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(6, 16),
            new Tretja.Strel(14, 1),
            new Tretja.Strel(15, 3),
            new Tretja.Strel(5, 6),
            new Tretja.Strel(0, 5),
            new Tretja.Strel(13, 11),
            new Tretja.Strel(15, 9),
            new Tretja.Strel(4, 5),
            new Tretja.Strel(5, 1),
            new Tretja.Strel(6, 10),
            new Tretja.Strel(11, 10),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(4, 3),
            new Tretja.Strel(10, 12),
            new Tretja.Strel(4, 7),
            new Tretja.Strel(1, 3),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(6, 11),
            new Tretja.Strel(9, 14),
            new Tretja.Strel(11, 7),
            new Tretja.Strel(12, 2),
            new Tretja.Strel(9, 0),
            new Tretja.Strel(15, 11),
            new Tretja.Strel(5, 5),
            new Tretja.Strel(3, 3),
            new Tretja.Strel(14, 13),
            new Tretja.Strel(16, 5),
            new Tretja.Strel(0, 2),
            new Tretja.Strel(8, 11),
            new Tretja.Strel(2, 12),
            new Tretja.Strel(5, 4),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(15, 6),
            new Tretja.Strel(12, 13),
            new Tretja.Strel(9, 8),
            new Tretja.Strel(7, 10),
            new Tretja.Strel(14, 3),
            new Tretja.Strel(2, 13),
            new Tretja.Strel(8, 0),
            new Tretja.Strel(3, 15),
            new Tretja.Strel(9, 16),
            new Tretja.Strel(0, 3),
            new Tretja.Strel(10, 0),
            new Tretja.Strel(1, 14),
            new Tretja.Strel(12, 11),
            new Tretja.Strel(8, 10),
            new Tretja.Strel(4, 16),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(7, 11),
            new Tretja.Strel(8, 2),
            new Tretja.Strel(3, 12),
            new Tretja.Strel(4, 8),
            new Tretja.Strel(14, 0),
            new Tretja.Strel(12, 6),
            new Tretja.Strel(2, 3),
            new Tretja.Strel(13, 10),
            new Tretja.Strel(5, 0),
            new Tretja.Strel(1, 12),
            new Tretja.Strel(0, 14),
            new Tretja.Strel(15, 15),
            new Tretja.Strel(3, 9),
            new Tretja.Strel(8, 9),
            new Tretja.Strel(16, 10),
            new Tretja.Strel(1, 10),
            new Tretja.Strel(15, 4),
            new Tretja.Strel(9, 15),
            new Tretja.Strel(6, 13),
            new Tretja.Strel(1, 0),
            new Tretja.Strel(2, 16),
            new Tretja.Strel(12, 1),
            new Tretja.Strel(6, 8),
            new Tretja.Strel(13, 8),
            new Tretja.Strel(6, 4),
            new Tretja.Strel(15, 8),
            new Tretja.Strel(13, 5),
            new Tretja.Strel(3, 7),
            new Tretja.Strel(1, 5),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(1, 11),
        };

        Tretja tretja = new Tretja(17, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat48.png", "544x646"}, "Potapljanje ladjic");
    }
}
