// _NE_ODSTRANI_

import java.awt.*;

public class Test40 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaNavpicno(9, 0, 5),
            new Tretja.LadjaVodoravno(12, 4, 10),
            new Tretja.LadjaVodoravno(10, 2, 14),
            new Tretja.LadjaNavpicno(0, 8, 5),
            new Tretja.LadjaVodoravno(6, 1, 15),
            new Tretja.LadjaNavpicno(8, 14, 1),
            new Tretja.LadjaVodoravno(15, 5, 9),
            new Tretja.LadjaVodoravno(8, 4, 9),
            new Tretja.LadjaNavpicno(2, 3, 2),
            new Tretja.LadjaNavpicno(3, 10, 2),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(4, 1),
            new Tretja.Strel(5, 5),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(0, 5),
            new Tretja.Strel(5, 0),
            new Tretja.Strel(4, 6),
            new Tretja.Strel(15, 15),
            new Tretja.Strel(6, 9),
            new Tretja.Strel(10, 2),
            new Tretja.Strel(6, 5),
            new Tretja.Strel(6, 13),
            new Tretja.Strel(14, 3),
            new Tretja.Strel(9, 8),
            new Tretja.Strel(7, 12),
            new Tretja.Strel(7, 13),
            new Tretja.Strel(4, 15),
            new Tretja.Strel(7, 15),
            new Tretja.Strel(2, 1),
            new Tretja.Strel(7, 2),
            new Tretja.Strel(12, 6),
            new Tretja.Strel(10, 14),
            new Tretja.Strel(11, 11),
            new Tretja.Strel(6, 11),
            new Tretja.Strel(9, 1),
            new Tretja.Strel(8, 7),
            new Tretja.Strel(3, 12),
            new Tretja.Strel(7, 9),
            new Tretja.Strel(4, 13),
            new Tretja.Strel(1, 14),
            new Tretja.Strel(8, 9),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(13, 9),
            new Tretja.Strel(1, 2),
            new Tretja.Strel(2, 15),
            new Tretja.Strel(10, 7),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(4, 3),
            new Tretja.Strel(3, 2),
            new Tretja.Strel(14, 5),
            new Tretja.Strel(11, 7),
            new Tretja.Strel(9, 15),
            new Tretja.Strel(2, 2),
            new Tretja.Strel(2, 5),
            new Tretja.Strel(10, 12),
            new Tretja.Strel(1, 13),
            new Tretja.Strel(8, 4),
            new Tretja.Strel(12, 13),
            new Tretja.Strel(6, 1),
            new Tretja.Strel(0, 7),
            new Tretja.Strel(7, 6),
            new Tretja.Strel(6, 6),
            new Tretja.Strel(11, 5),
            new Tretja.Strel(8, 8),
            new Tretja.Strel(0, 4),
            new Tretja.Strel(11, 8),
            new Tretja.Strel(12, 7),
            new Tretja.Strel(12, 9),
            new Tretja.Strel(9, 2),
            new Tretja.Strel(14, 6),
            new Tretja.Strel(3, 13),
            new Tretja.Strel(13, 8),
            new Tretja.Strel(0, 9),
            new Tretja.Strel(9, 11),
            new Tretja.Strel(2, 7),
            new Tretja.Strel(2, 10),
            new Tretja.Strel(7, 14),
            new Tretja.Strel(9, 0),
            new Tretja.Strel(10, 10),
            new Tretja.Strel(0, 0),
            new Tretja.Strel(8, 14),
            new Tretja.Strel(15, 2),
            new Tretja.Strel(12, 2),
            new Tretja.Strel(5, 6),
            new Tretja.Strel(10, 13),
            new Tretja.Strel(7, 5),
            new Tretja.Strel(0, 11),
            new Tretja.Strel(8, 6),
            new Tretja.Strel(7, 3),
            new Tretja.Strel(9, 6),
            new Tretja.Strel(6, 8),
            new Tretja.Strel(14, 2),
            new Tretja.Strel(7, 8),
            new Tretja.Strel(2, 9),
            new Tretja.Strel(2, 13),
            new Tretja.Strel(9, 13),
            new Tretja.Strel(3, 10),
            new Tretja.Strel(10, 9),
            new Tretja.Strel(2, 11),
            new Tretja.Strel(9, 5),
            new Tretja.Strel(10, 5),
            new Tretja.Strel(6, 12),
            new Tretja.Strel(14, 10),
            new Tretja.Strel(8, 0),
            new Tretja.Strel(12, 5),
            new Tretja.Strel(7, 10),
            new Tretja.Strel(12, 15),
            new Tretja.Strel(8, 15),
            new Tretja.Strel(15, 13),
            new Tretja.Strel(6, 2),
            new Tretja.Strel(15, 14),
            new Tretja.Strel(4, 5),
            new Tretja.Strel(5, 7),
            new Tretja.Strel(13, 10),
            new Tretja.Strel(10, 1),
            new Tretja.Strel(9, 4),
            new Tretja.Strel(9, 12),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(15, 7),
            new Tretja.Strel(3, 14),
            new Tretja.Strel(4, 0),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(1, 11),
        };

        Tretja tretja = new Tretja(16, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat40.png", "576x800"}, "Potapljanje ladjic");
    }
}
