// _NE_ODSTRANI_

import java.awt.*;

public class Test28 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {};
        Tretja.Strel[] streli = {
            new Tretja.Strel(11, 3),
            new Tretja.Strel(8, 4),
            new Tretja.Strel(12, 0),
            new Tretja.Strel(3, 5),
            new Tretja.Strel(4, 7),
            new Tretja.Strel(0, 12),
            new Tretja.Strel(4, 9),
            new Tretja.Strel(11, 0),
            new Tretja.Strel(0, 8),
            new Tretja.Strel(9, 7),
            new Tretja.Strel(0, 4),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(7, 5),
            new Tretja.Strel(4, 6),
            new Tretja.Strel(12, 11),
            new Tretja.Strel(5, 8),
            new Tretja.Strel(11, 11),
            new Tretja.Strel(4, 4),
            new Tretja.Strel(1, 3),
            new Tretja.Strel(5, 3),
            new Tretja.Strel(7, 9),
            new Tretja.Strel(1, 0),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(1, 6),
            new Tretja.Strel(2, 4),
            new Tretja.Strel(1, 2),
            new Tretja.Strel(11, 6),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(0, 6),
            new Tretja.Strel(8, 6),
            new Tretja.Strel(9, 8),
            new Tretja.Strel(3, 4),
            new Tretja.Strel(0, 11),
            new Tretja.Strel(8, 1),
            new Tretja.Strel(5, 0),
            new Tretja.Strel(1, 12),
            new Tretja.Strel(4, 8),
            new Tretja.Strel(1, 10),
            new Tretja.Strel(1, 8),
            new Tretja.Strel(7, 1),
            new Tretja.Strel(6, 9),
            new Tretja.Strel(7, 2),
            new Tretja.Strel(12, 6),
            new Tretja.Strel(1, 7),
            new Tretja.Strel(9, 11),
            new Tretja.Strel(6, 8),
            new Tretja.Strel(1, 5),
            new Tretja.Strel(12, 9),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(6, 6),
            new Tretja.Strel(12, 8),
            new Tretja.Strel(10, 3),
            new Tretja.Strel(3, 6),
            new Tretja.Strel(9, 10),
            new Tretja.Strel(11, 10),
            new Tretja.Strel(7, 11),
            new Tretja.Strel(9, 5),
            new Tretja.Strel(1, 11),
            new Tretja.Strel(8, 7),
            new Tretja.Strel(2, 11),
            new Tretja.Strel(2, 1),
            new Tretja.Strel(8, 12),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(12, 7),
            new Tretja.Strel(9, 1),
            new Tretja.Strel(3, 11),
        };

        Tretja tretja = new Tretja(13, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat28.png", "520x806"}, "Potapljanje ladjic");
    }
}
