// _NE_ODSTRANI_

import java.awt.*;

public class Test11 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {};
        Tretja.Strel[] streli = {
            new Tretja.Strel(0, 0),
            new Tretja.Strel(6, 10),
            new Tretja.Strel(11, 10),
            new Tretja.Strel(2, 13),
            new Tretja.Strel(18, 6),
            new Tretja.Strel(2, 7),
            new Tretja.Strel(1, 3),
            new Tretja.Strel(8, 12),
            new Tretja.Strel(19, 2),
            new Tretja.Strel(15, 19),
            new Tretja.Strel(12, 3),
            new Tretja.Strel(11, 7),
            new Tretja.Strel(10, 18),
            new Tretja.Strel(19, 3),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(16, 19),
            new Tretja.Strel(10, 7),
            new Tretja.Strel(4, 8),
            new Tretja.Strel(12, 9),
            new Tretja.Strel(3, 5),
            new Tretja.Strel(7, 15),
            new Tretja.Strel(13, 19),
            new Tretja.Strel(1, 11),
            new Tretja.Strel(8, 8),
            new Tretja.Strel(4, 13),
            new Tretja.Strel(6, 7),
            new Tretja.Strel(9, 11),
            new Tretja.Strel(15, 14),
            new Tretja.Strel(13, 13),
            new Tretja.Strel(18, 18),
            new Tretja.Strel(14, 18),
            new Tretja.Strel(4, 2),
            new Tretja.Strel(0, 16),
            new Tretja.Strel(0, 7),
            new Tretja.Strel(7, 8),
            new Tretja.Strel(4, 4),
            new Tretja.Strel(17, 19),
            new Tretja.Strel(18, 0),
            new Tretja.Strel(19, 11),
            new Tretja.Strel(12, 15),
            new Tretja.Strel(16, 14),
            new Tretja.Strel(0, 8),
            new Tretja.Strel(4, 9),
            new Tretja.Strel(16, 4),
            new Tretja.Strel(12, 13),
            new Tretja.Strel(17, 4),
            new Tretja.Strel(14, 16),
            new Tretja.Strel(17, 16),
            new Tretja.Strel(9, 0),
            new Tretja.Strel(3, 10),
            new Tretja.Strel(14, 12),
            new Tretja.Strel(6, 6),
            new Tretja.Strel(7, 19),
            new Tretja.Strel(3, 15),
            new Tretja.Strel(11, 14),
            new Tretja.Strel(8, 3),
            new Tretja.Strel(3, 6),
            new Tretja.Strel(11, 17),
            new Tretja.Strel(6, 8),
            new Tretja.Strel(2, 4),
            new Tretja.Strel(13, 12),
            new Tretja.Strel(0, 3),
            new Tretja.Strel(15, 17),
            new Tretja.Strel(15, 5),
            new Tretja.Strel(14, 0),
            new Tretja.Strel(11, 18),
            new Tretja.Strel(4, 19),
            new Tretja.Strel(16, 11),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(15, 6),
            new Tretja.Strel(2, 18),
            new Tretja.Strel(7, 12),
            new Tretja.Strel(18, 4),
            new Tretja.Strel(6, 15),
            new Tretja.Strel(14, 2),
            new Tretja.Strel(12, 19),
            new Tretja.Strel(10, 16),
            new Tretja.Strel(16, 7),
            new Tretja.Strel(11, 1),
            new Tretja.Strel(4, 7),
            new Tretja.Strel(18, 2),
            new Tretja.Strel(2, 14),
            new Tretja.Strel(18, 7),
            new Tretja.Strel(3, 12),
            new Tretja.Strel(2, 12),
            new Tretja.Strel(10, 2),
            new Tretja.Strel(10, 11),
            new Tretja.Strel(10, 19),
            new Tretja.Strel(7, 0),
            new Tretja.Strel(13, 6),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(13, 17),
            new Tretja.Strel(5, 9),
            new Tretja.Strel(1, 9),
            new Tretja.Strel(14, 3),
            new Tretja.Strel(13, 11),
            new Tretja.Strel(11, 8),
            new Tretja.Strel(7, 11),
            new Tretja.Strel(5, 13),
            new Tretja.Strel(14, 19),
            new Tretja.Strel(0, 10),
            new Tretja.Strel(13, 10),
            new Tretja.Strel(17, 15),
            new Tretja.Strel(3, 4),
            new Tretja.Strel(7, 3),
            new Tretja.Strel(5, 2),
            new Tretja.Strel(11, 3),
            new Tretja.Strel(10, 3),
            new Tretja.Strel(3, 9),
            new Tretja.Strel(13, 1),
            new Tretja.Strel(11, 13),
            new Tretja.Strel(9, 9),
            new Tretja.Strel(3, 13),
            new Tretja.Strel(0, 18),
            new Tretja.Strel(0, 19),
            new Tretja.Strel(17, 18),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(17, 5),
            new Tretja.Strel(6, 5),
            new Tretja.Strel(1, 15),
            new Tretja.Strel(2, 3),
            new Tretja.Strel(0, 11),
            new Tretja.Strel(1, 16),
            new Tretja.Strel(17, 6),
            new Tretja.Strel(13, 16),
            new Tretja.Strel(14, 10),
            new Tretja.Strel(17, 12),
            new Tretja.Strel(15, 10),
            new Tretja.Strel(9, 17),
            new Tretja.Strel(6, 9),
            new Tretja.Strel(18, 3),
            new Tretja.Strel(12, 17),
            new Tretja.Strel(2, 9),
            new Tretja.Strel(19, 6),
            new Tretja.Strel(3, 2),
            new Tretja.Strel(16, 0),
            new Tretja.Strel(14, 9),
            new Tretja.Strel(19, 12),
            new Tretja.Strel(0, 2),
            new Tretja.Strel(14, 1),
            new Tretja.Strel(10, 12),
            new Tretja.Strel(1, 18),
        };

        Tretja tretja = new Tretja(20, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat11.png", "520x520"}, "Potapljanje ladjic");
    }
}
