// _NE_ODSTRANI_

import java.awt.*;

public class Test25 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaVodoravno(10, 3, 11),
            new Tretja.LadjaVodoravno(7, 2, 10),
            new Tretja.LadjaVodoravno(2, 6, 5),
            new Tretja.LadjaNavpicno(13, 0, 2),
            new Tretja.LadjaNavpicno(0, 3, 5),
            new Tretja.LadjaNavpicno(0, 16, 16),
            new Tretja.LadjaVodoravno(16, 0, 15),
            new Tretja.LadjaVodoravno(0, 5, 10),
            new Tretja.LadjaVodoravno(12, 3, 2),
            new Tretja.LadjaNavpicno(0, 0, 12),
            new Tretja.LadjaNavpicno(2, 14, 7),
            new Tretja.LadjaVodoravno(14, 4, 2),
            new Tretja.LadjaVodoravno(12, 9, 6),
            new Tretja.LadjaNavpicno(2, 12, 2),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(1, 6),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(1, 7),
            new Tretja.Strel(8, 12),
            new Tretja.Strel(15, 13),
            new Tretja.Strel(12, 2),
            new Tretja.Strel(11, 0),
            new Tretja.Strel(15, 7),
            new Tretja.Strel(16, 2),
            new Tretja.Strel(15, 3),
            new Tretja.Strel(11, 8),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(8, 10),
            new Tretja.Strel(2, 5),
            new Tretja.Strel(2, 4),
            new Tretja.Strel(7, 6),
            new Tretja.Strel(10, 11),
            new Tretja.Strel(12, 14),
            new Tretja.Strel(14, 13),
            new Tretja.Strel(10, 9),
            new Tretja.Strel(13, 5),
            new Tretja.Strel(14, 11),
            new Tretja.Strel(13, 12),
            new Tretja.Strel(5, 5),
            new Tretja.Strel(2, 2),
            new Tretja.Strel(13, 8),
            new Tretja.Strel(12, 0),
            new Tretja.Strel(16, 1),
            new Tretja.Strel(11, 3),
            new Tretja.Strel(6, 4),
            new Tretja.Strel(9, 16),
            new Tretja.Strel(14, 12),
            new Tretja.Strel(4, 6),
            new Tretja.Strel(0, 9),
            new Tretja.Strel(11, 5),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(8, 3),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(16, 9),
            new Tretja.Strel(1, 10),
            new Tretja.Strel(1, 9),
            new Tretja.Strel(13, 13),
            new Tretja.Strel(5, 13),
            new Tretja.Strel(9, 1),
            new Tretja.Strel(6, 0),
            new Tretja.Strel(10, 1),
            new Tretja.Strel(11, 14),
            new Tretja.Strel(10, 7),
            new Tretja.Strel(5, 16),
            new Tretja.Strel(12, 13),
            new Tretja.Strel(13, 9),
            new Tretja.Strel(14, 9),
            new Tretja.Strel(1, 8),
            new Tretja.Strel(7, 15),
            new Tretja.Strel(9, 11),
            new Tretja.Strel(11, 6),
            new Tretja.Strel(4, 4),
            new Tretja.Strel(14, 6),
            new Tretja.Strel(16, 14),
            new Tretja.Strel(9, 5),
            new Tretja.Strel(7, 7),
            new Tretja.Strel(2, 8),
            new Tretja.Strel(16, 0),
            new Tretja.Strel(9, 10),
            new Tretja.Strel(12, 16),
            new Tretja.Strel(8, 0),
            new Tretja.Strel(3, 12),
            new Tretja.Strel(0, 3),
            new Tretja.Strel(9, 7),
            new Tretja.Strel(14, 0),
            new Tretja.Strel(4, 14),
            new Tretja.Strel(3, 10),
            new Tretja.Strel(9, 4),
            new Tretja.Strel(7, 12),
            new Tretja.Strel(2, 3),
            new Tretja.Strel(12, 7),
            new Tretja.Strel(1, 0),
            new Tretja.Strel(7, 9),
            new Tretja.Strel(7, 0),
            new Tretja.Strel(13, 7),
        };

        Tretja tretja = new Tretja(17, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat25.png", "612x612"}, "Potapljanje ladjic");
    }
}
