// _NE_ODSTRANI_

import java.awt.*;

public class Test45 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaNavpicno(1, 11, 6),
            new Tretja.LadjaNavpicno(14, 12, 2),
            new Tretja.LadjaVodoravno(8, 2, 5),
            new Tretja.LadjaNavpicno(0, 8, 19),
            new Tretja.LadjaNavpicno(15, 4, 2),
            new Tretja.LadjaNavpicno(2, 16, 10),
            new Tretja.LadjaNavpicno(7, 0, 4),
            new Tretja.LadjaVodoravno(12, 10, 5),
            new Tretja.LadjaVodoravno(17, 11, 8),
            new Tretja.LadjaVodoravno(1, 3, 1),
            new Tretja.LadjaVodoravno(12, 2, 1),
            new Tretja.LadjaNavpicno(2, 18, 9),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(6, 3),
            new Tretja.Strel(4, 17),
            new Tretja.Strel(16, 13),
            new Tretja.Strel(13, 18),
            new Tretja.Strel(6, 0),
            new Tretja.Strel(8, 3),
            new Tretja.Strel(18, 6),
            new Tretja.Strel(14, 16),
            new Tretja.Strel(17, 5),
            new Tretja.Strel(7, 3),
            new Tretja.Strel(2, 3),
            new Tretja.Strel(11, 18),
            new Tretja.Strel(1, 12),
            new Tretja.Strel(3, 8),
            new Tretja.Strel(17, 9),
            new Tretja.Strel(12, 16),
            new Tretja.Strel(2, 11),
            new Tretja.Strel(7, 16),
            new Tretja.Strel(3, 15),
            new Tretja.Strel(6, 10),
            new Tretja.Strel(17, 10),
            new Tretja.Strel(9, 4),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(0, 5),
            new Tretja.Strel(8, 18),
            new Tretja.Strel(7, 15),
            new Tretja.Strel(11, 8),
            new Tretja.Strel(8, 17),
            new Tretja.Strel(13, 7),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(18, 10),
            new Tretja.Strel(7, 8),
            new Tretja.Strel(3, 9),
            new Tretja.Strel(18, 16),
            new Tretja.Strel(13, 6),
            new Tretja.Strel(6, 16),
            new Tretja.Strel(0, 14),
            new Tretja.Strel(4, 9),
            new Tretja.Strel(11, 0),
            new Tretja.Strel(15, 4),
            new Tretja.Strel(16, 18),
            new Tretja.Strel(16, 11),
            new Tretja.Strel(13, 16),
            new Tretja.Strel(16, 7),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(13, 3),
            new Tretja.Strel(3, 6),
            new Tretja.Strel(3, 16),
            new Tretja.Strel(1, 4),
            new Tretja.Strel(0, 15),
            new Tretja.Strel(6, 7),
            new Tretja.Strel(16, 14),
            new Tretja.Strel(2, 10),
            new Tretja.Strel(7, 5),
            new Tretja.Strel(13, 9),
            new Tretja.Strel(16, 6),
            new Tretja.Strel(8, 5),
            new Tretja.Strel(3, 4),
            new Tretja.Strel(7, 13),
            new Tretja.Strel(11, 10),
            new Tretja.Strel(8, 4),
            new Tretja.Strel(9, 12),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(6, 13),
            new Tretja.Strel(12, 18),
            new Tretja.Strel(0, 3),
            new Tretja.Strel(7, 0),
            new Tretja.Strel(16, 15),
            new Tretja.Strel(2, 13),
            new Tretja.Strel(2, 17),
            new Tretja.Strel(6, 1),
            new Tretja.Strel(15, 8),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(16, 3),
            new Tretja.Strel(6, 2),
            new Tretja.Strel(2, 15),
            new Tretja.Strel(12, 9),
            new Tretja.Strel(2, 14),
            new Tretja.Strel(12, 14),
            new Tretja.Strel(17, 6),
            new Tretja.Strel(18, 0),
            new Tretja.Strel(7, 9),
            new Tretja.Strel(0, 17),
            new Tretja.Strel(5, 0),
            new Tretja.Strel(17, 17),
            new Tretja.Strel(5, 9),
            new Tretja.Strel(10, 6),
            new Tretja.Strel(5, 14),
            new Tretja.Strel(17, 4),
            new Tretja.Strel(8, 2),
            new Tretja.Strel(15, 13),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(16, 2),
            new Tretja.Strel(8, 0),
            new Tretja.Strel(2, 0),
            new Tretja.Strel(8, 15),
            new Tretja.Strel(12, 17),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(5, 18),
            new Tretja.Strel(10, 2),
            new Tretja.Strel(8, 6),
            new Tretja.Strel(0, 11),
            new Tretja.Strel(1, 13),
            new Tretja.Strel(12, 12),
            new Tretja.Strel(9, 13),
            new Tretja.Strel(10, 17),
            new Tretja.Strel(7, 11),
            new Tretja.Strel(0, 16),
            new Tretja.Strel(16, 5),
            new Tretja.Strel(15, 14),
            new Tretja.Strel(0, 8),
            new Tretja.Strel(12, 15),
            new Tretja.Strel(4, 8),
            new Tretja.Strel(11, 14),
            new Tretja.Strel(11, 15),
            new Tretja.Strel(14, 2),
            new Tretja.Strel(15, 5),
            new Tretja.Strel(10, 1),
            new Tretja.Strel(16, 12),
            new Tretja.Strel(0, 7),
            new Tretja.Strel(13, 17),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(9, 16),
            new Tretja.Strel(11, 6),
            new Tretja.Strel(10, 7),
            new Tretja.Strel(9, 14),
            new Tretja.Strel(14, 5),
            new Tretja.Strel(16, 8),
            new Tretja.Strel(14, 4),
            new Tretja.Strel(8, 1),
            new Tretja.Strel(12, 5),
            new Tretja.Strel(17, 1),
            new Tretja.Strel(16, 0),
            new Tretja.Strel(17, 0),
            new Tretja.Strel(8, 9),
            new Tretja.Strel(14, 12),
            new Tretja.Strel(3, 12),
            new Tretja.Strel(10, 18),
            new Tretja.Strel(2, 2),
            new Tretja.Strel(4, 0),
            new Tretja.Strel(17, 14),
            new Tretja.Strel(4, 18),
            new Tretja.Strel(15, 18),
            new Tretja.Strel(18, 14),
            new Tretja.Strel(18, 2),
            new Tretja.Strel(16, 9),
            new Tretja.Strel(10, 5),
            new Tretja.Strel(11, 9),
            new Tretja.Strel(8, 11),
            new Tretja.Strel(3, 2),
            new Tretja.Strel(10, 10),
            new Tretja.Strel(15, 10),
            new Tretja.Strel(9, 2),
        };

        Tretja tretja = new Tretja(19, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat45.png", "722x646"}, "Potapljanje ladjic");
    }
}
