// _NE_ODSTRANI_

import java.awt.*;

public class Test13 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {};
        Tretja.Strel[] streli = {
            new Tretja.Strel(9, 8),
            new Tretja.Strel(8, 15),
            new Tretja.Strel(15, 10),
            new Tretja.Strel(5, 1),
            new Tretja.Strel(3, 5),
            new Tretja.Strel(6, 1),
            new Tretja.Strel(13, 7),
            new Tretja.Strel(2, 11),
            new Tretja.Strel(14, 16),
            new Tretja.Strel(16, 0),
            new Tretja.Strel(3, 8),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(13, 2),
            new Tretja.Strel(5, 14),
            new Tretja.Strel(5, 5),
            new Tretja.Strel(7, 14),
            new Tretja.Strel(11, 0),
            new Tretja.Strel(8, 3),
            new Tretja.Strel(16, 2),
            new Tretja.Strel(1, 11),
            new Tretja.Strel(15, 8),
            new Tretja.Strel(9, 7),
            new Tretja.Strel(8, 14),
            new Tretja.Strel(12, 15),
            new Tretja.Strel(6, 9),
            new Tretja.Strel(10, 2),
            new Tretja.Strel(8, 1),
            new Tretja.Strel(11, 6),
            new Tretja.Strel(15, 1),
            new Tretja.Strel(6, 16),
            new Tretja.Strel(6, 11),
            new Tretja.Strel(9, 16),
            new Tretja.Strel(16, 13),
            new Tretja.Strel(14, 4),
            new Tretja.Strel(7, 13),
            new Tretja.Strel(3, 2),
            new Tretja.Strel(14, 7),
            new Tretja.Strel(9, 13),
            new Tretja.Strel(8, 16),
            new Tretja.Strel(1, 1),
            new Tretja.Strel(8, 10),
            new Tretja.Strel(6, 5),
            new Tretja.Strel(0, 0),
            new Tretja.Strel(7, 11),
            new Tretja.Strel(7, 9),
            new Tretja.Strel(6, 13),
            new Tretja.Strel(16, 7),
            new Tretja.Strel(2, 16),
            new Tretja.Strel(16, 12),
            new Tretja.Strel(13, 16),
            new Tretja.Strel(11, 1),
            new Tretja.Strel(13, 1),
            new Tretja.Strel(6, 7),
            new Tretja.Strel(16, 15),
            new Tretja.Strel(12, 5),
            new Tretja.Strel(16, 16),
            new Tretja.Strel(12, 8),
            new Tretja.Strel(3, 6),
            new Tretja.Strel(16, 5),
            new Tretja.Strel(12, 16),
            new Tretja.Strel(7, 1),
            new Tretja.Strel(1, 15),
            new Tretja.Strel(9, 5),
            new Tretja.Strel(2, 5),
            new Tretja.Strel(7, 6),
            new Tretja.Strel(7, 10),
            new Tretja.Strel(4, 0),
            new Tretja.Strel(13, 9),
            new Tretja.Strel(16, 11),
            new Tretja.Strel(4, 3),
            new Tretja.Strel(10, 0),
            new Tretja.Strel(3, 9),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(12, 11),
            new Tretja.Strel(0, 16),
            new Tretja.Strel(12, 0),
            new Tretja.Strel(7, 5),
            new Tretja.Strel(5, 3),
            new Tretja.Strel(1, 3),
            new Tretja.Strel(5, 7),
            new Tretja.Strel(12, 4),
            new Tretja.Strel(13, 15),
            new Tretja.Strel(1, 0),
            new Tretja.Strel(7, 4),
            new Tretja.Strel(15, 2),
            new Tretja.Strel(0, 1),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(10, 12),
            new Tretja.Strel(7, 2),
            new Tretja.Strel(13, 10),
            new Tretja.Strel(14, 9),
            new Tretja.Strel(4, 6),
        };

        Tretja tretja = new Tretja(17, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat13.png", "782x782"}, "Potapljanje ladjic");
    }
}
