// _NE_ODSTRANI_

import java.awt.*;

public class Test41 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaVodoravno(6, 0, 17),
            new Tretja.LadjaVodoravno(4, 11, 9),
            new Tretja.LadjaNavpicno(12, 9, 5),
            new Tretja.LadjaNavpicno(8, 17, 12),
            new Tretja.LadjaVodoravno(2, 6, 14),
            new Tretja.LadjaNavpicno(10, 4, 10),
            new Tretja.LadjaNavpicno(0, 12, 1),
            new Tretja.LadjaVodoravno(19, 6, 10),
            new Tretja.LadjaNavpicno(8, 14, 10),
            new Tretja.LadjaVodoravno(8, 1, 11),
            new Tretja.LadjaNavpicno(9, 19, 9),
            new Tretja.LadjaNavpicno(10, 12, 7),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(1, 9),
            new Tretja.Strel(2, 2),
            new Tretja.Strel(5, 8),
            new Tretja.Strel(6, 9),
            new Tretja.Strel(9, 17),
            new Tretja.Strel(12, 2),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(3, 4),
            new Tretja.Strel(8, 15),
            new Tretja.Strel(0, 16),
            new Tretja.Strel(2, 14),
            new Tretja.Strel(11, 6),
            new Tretja.Strel(14, 10),
            new Tretja.Strel(0, 13),
            new Tretja.Strel(11, 15),
            new Tretja.Strel(9, 7),
            new Tretja.Strel(16, 2),
            new Tretja.Strel(5, 17),
            new Tretja.Strel(4, 17),
            new Tretja.Strel(16, 3),
            new Tretja.Strel(7, 5),
            new Tretja.Strel(10, 15),
            new Tretja.Strel(17, 3),
            new Tretja.Strel(10, 13),
            new Tretja.Strel(3, 17),
            new Tretja.Strel(1, 5),
            new Tretja.Strel(7, 9),
            new Tretja.Strel(18, 18),
            new Tretja.Strel(19, 7),
            new Tretja.Strel(19, 1),
            new Tretja.Strel(4, 10),
            new Tretja.Strel(7, 1),
            new Tretja.Strel(6, 11),
            new Tretja.Strel(7, 16),
            new Tretja.Strel(5, 0),
            new Tretja.Strel(1, 10),
            new Tretja.Strel(12, 13),
            new Tretja.Strel(18, 13),
            new Tretja.Strel(9, 9),
            new Tretja.Strel(5, 12),
            new Tretja.Strel(6, 12),
            new Tretja.Strel(15, 5),
            new Tretja.Strel(17, 11),
            new Tretja.Strel(0, 8),
            new Tretja.Strel(1, 18),
            new Tretja.Strel(6, 16),
            new Tretja.Strel(0, 19),
            new Tretja.Strel(1, 13),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(7, 0),
            new Tretja.Strel(7, 13),
            new Tretja.Strel(1, 11),
            new Tretja.Strel(14, 17),
            new Tretja.Strel(13, 5),
            new Tretja.Strel(16, 4),
            new Tretja.Strel(2, 15),
            new Tretja.Strel(15, 12),
            new Tretja.Strel(0, 14),
            new Tretja.Strel(15, 9),
            new Tretja.Strel(8, 7),
            new Tretja.Strel(5, 15),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(5, 3),
            new Tretja.Strel(16, 12),
            new Tretja.Strel(8, 13),
            new Tretja.Strel(18, 6),
            new Tretja.Strel(13, 7),
            new Tretja.Strel(14, 12),
            new Tretja.Strel(12, 19),
            new Tretja.Strel(2, 5),
            new Tretja.Strel(13, 11),
            new Tretja.Strel(19, 16),
            new Tretja.Strel(0, 2),
            new Tretja.Strel(15, 8),
            new Tretja.Strel(15, 1),
            new Tretja.Strel(6, 1),
            new Tretja.Strel(18, 4),
            new Tretja.Strel(5, 9),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(19, 2),
            new Tretja.Strel(5, 6),
            new Tretja.Strel(18, 19),
            new Tretja.Strel(1, 16),
            new Tretja.Strel(2, 18),
            new Tretja.Strel(4, 15),
            new Tretja.Strel(9, 18),
            new Tretja.Strel(12, 3),
            new Tretja.Strel(13, 19),
            new Tretja.Strel(11, 19),
            new Tretja.Strel(1, 2),
            new Tretja.Strel(12, 18),
            new Tretja.Strel(17, 8),
            new Tretja.Strel(5, 7),
            new Tretja.Strel(1, 17),
            new Tretja.Strel(18, 0),
            new Tretja.Strel(19, 13),
            new Tretja.Strel(15, 4),
            new Tretja.Strel(19, 10),
            new Tretja.Strel(2, 17),
            new Tretja.Strel(13, 2),
            new Tretja.Strel(8, 14),
            new Tretja.Strel(17, 4),
            new Tretja.Strel(0, 11),
            new Tretja.Strel(18, 9),
            new Tretja.Strel(12, 5),
            new Tretja.Strel(9, 3),
            new Tretja.Strel(10, 1),
            new Tretja.Strel(19, 19),
            new Tretja.Strel(0, 1),
            new Tretja.Strel(3, 14),
            new Tretja.Strel(13, 17),
            new Tretja.Strel(14, 8),
            new Tretja.Strel(17, 15),
            new Tretja.Strel(16, 7),
            new Tretja.Strel(10, 17),
            new Tretja.Strel(19, 3),
            new Tretja.Strel(8, 12),
            new Tretja.Strel(7, 17),
            new Tretja.Strel(13, 1),
            new Tretja.Strel(15, 15),
        };

        Tretja tretja = new Tretja(20, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat41.png", "480x760"}, "Potapljanje ladjic");
    }
}
