// _NE_ODSTRANI_

import java.awt.*;

public class Test36 {

    public static void main(String[] args) {

        Tretja.Ladja[] ladje = {
            new Tretja.LadjaVodoravno(7, 7, 1),
            new Tretja.LadjaVodoravno(2, 3, 8),
            new Tretja.LadjaVodoravno(13, 3, 1),
            new Tretja.LadjaNavpicno(10, 13, 3),
            new Tretja.LadjaVodoravno(10, 0, 10),
            new Tretja.LadjaNavpicno(4, 11, 11),
            new Tretja.LadjaNavpicno(1, 15, 11),
            new Tretja.LadjaVodoravno(0, 1, 11),
            new Tretja.LadjaVodoravno(5, 2, 6),
            new Tretja.LadjaVodoravno(7, 0, 4),
            new Tretja.LadjaNavpicno(0, 13, 9),
            new Tretja.LadjaNavpicno(5, 9, 2),
        };
        Tretja.Strel[] streli = {
            new Tretja.Strel(0, 14),
            new Tretja.Strel(0, 15),
            new Tretja.Strel(5, 9),
            new Tretja.Strel(5, 15),
            new Tretja.Strel(7, 10),
            new Tretja.Strel(9, 5),
            new Tretja.Strel(14, 10),
            new Tretja.Strel(10, 8),
            new Tretja.Strel(11, 1),
            new Tretja.Strel(7, 15),
            new Tretja.Strel(13, 7),
            new Tretja.Strel(5, 2),
            new Tretja.Strel(12, 14),
            new Tretja.Strel(9, 7),
            new Tretja.Strel(2, 14),
            new Tretja.Strel(13, 4),
            new Tretja.Strel(5, 10),
            new Tretja.Strel(8, 1),
            new Tretja.Strel(14, 3),
            new Tretja.Strel(2, 6),
            new Tretja.Strel(1, 5),
            new Tretja.Strel(15, 14),
            new Tretja.Strel(15, 3),
            new Tretja.Strel(3, 7),
            new Tretja.Strel(1, 4),
            new Tretja.Strel(3, 6),
            new Tretja.Strel(10, 14),
            new Tretja.Strel(13, 12),
            new Tretja.Strel(6, 11),
            new Tretja.Strel(14, 0),
            new Tretja.Strel(8, 9),
            new Tretja.Strel(6, 6),
            new Tretja.Strel(0, 12),
            new Tretja.Strel(0, 9),
            new Tretja.Strel(11, 8),
            new Tretja.Strel(9, 6),
            new Tretja.Strel(6, 15),
            new Tretja.Strel(3, 10),
            new Tretja.Strel(4, 1),
            new Tretja.Strel(0, 1),
            new Tretja.Strel(12, 8),
            new Tretja.Strel(2, 13),
            new Tretja.Strel(8, 13),
            new Tretja.Strel(4, 4),
            new Tretja.Strel(7, 2),
            new Tretja.Strel(15, 13),
            new Tretja.Strel(4, 12),
            new Tretja.Strel(2, 2),
            new Tretja.Strel(6, 3),
            new Tretja.Strel(6, 10),
            new Tretja.Strel(3, 1),
            new Tretja.Strel(1, 6),
            new Tretja.Strel(4, 15),
            new Tretja.Strel(8, 3),
            new Tretja.Strel(6, 9),
            new Tretja.Strel(12, 9),
            new Tretja.Strel(11, 13),
            new Tretja.Strel(11, 7),
            new Tretja.Strel(4, 8),
            new Tretja.Strel(12, 7),
            new Tretja.Strel(4, 11),
            new Tretja.Strel(2, 4),
            new Tretja.Strel(8, 14),
            new Tretja.Strel(14, 7),
            new Tretja.Strel(9, 12),
            new Tretja.Strel(11, 11),
            new Tretja.Strel(9, 2),
            new Tretja.Strel(13, 1),
            new Tretja.Strel(14, 5),
            new Tretja.Strel(12, 0),
            new Tretja.Strel(0, 8),
            new Tretja.Strel(15, 8),
            new Tretja.Strel(2, 1),
            new Tretja.Strel(3, 3),
            new Tretja.Strel(1, 2),
            new Tretja.Strel(5, 3),
            new Tretja.Strel(13, 15),
            new Tretja.Strel(1, 7),
            new Tretja.Strel(7, 1),
            new Tretja.Strel(5, 12),
            new Tretja.Strel(9, 14),
            new Tretja.Strel(12, 2),
            new Tretja.Strel(5, 14),
            new Tretja.Strel(1, 14),
            new Tretja.Strel(2, 9),
            new Tretja.Strel(14, 1),
            new Tretja.Strel(12, 4),
            new Tretja.Strel(7, 6),
            new Tretja.Strel(11, 10),
            new Tretja.Strel(9, 9),
            new Tretja.Strel(2, 11),
            new Tretja.Strel(7, 11),
            new Tretja.Strel(4, 9),
            new Tretja.Strel(13, 3),
            new Tretja.Strel(9, 11),
            new Tretja.Strel(0, 2),
            new Tretja.Strel(9, 0),
            new Tretja.Strel(14, 13),
            new Tretja.Strel(5, 1),
            new Tretja.Strel(5, 7),
            new Tretja.Strel(12, 13),
            new Tretja.Strel(14, 11),
            new Tretja.Strel(11, 12),
            new Tretja.Strel(11, 2),
            new Tretja.Strel(5, 8),
            new Tretja.Strel(0, 11),
            new Tretja.Strel(11, 3),
            new Tretja.Strel(14, 9),
            new Tretja.Strel(1, 0),
            new Tretja.Strel(3, 0),
            new Tretja.Strel(11, 6),
            new Tretja.Strel(4, 6),
            new Tretja.Strel(7, 3),
            new Tretja.Strel(15, 11),
            new Tretja.Strel(0, 7),
            new Tretja.Strel(4, 3),
            new Tretja.Strel(13, 2),
            new Tretja.Strel(0, 10),
        };

        Tretja tretja = new Tretja(16, ladje, streli);
        tretja.sproziRisanje(new String[]{"rezultat36.png", "704x480"}, "Potapljanje ladjic");
    }
}
